### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by omarroth** [iv-org/invidious#108]
For Invidious accounts, there is no way to reset a password, which means a user is locked out of their account if they forget their password. Because Invidious only requires a User ID and password, there is no way to send a `password reset` email or anything.

I'm curious if there is a good way to reset a user's password using only the information Invidious stores about the user.

**Comment by PrestonN** [comment]
Just going to throw out a couple of suggestions for this.

* Have the user submit security questions.  Probably make both the question and answer user submitted.  Maybe allow / force them to submit multiple questions and only when a few are answered can they change the password.

* Generate one / several one time passwords upon account creation.  The user would be expected to secure these somewhere local or through a paper backup.  Using one would force a password change when used and cannot be used again.

* Make email accounts optional.  Not providing an email would simply make a password reset impossible.  I believe this is what Reddit does.

Any of these should be enough.  Users should be aware of the risks with minimal account creation and remembering / storing their password should be their responsibility.  This is the trade off that they get for better privacy.

**Comment by omarroth** [comment]
Very interesting, thank you!

**Comment by reustle** [comment]
It boggles my mind that this is still not implemented. Sending a password reset email is such a critical piece. While yes I agree everyone should be using a password manager, sometimes it doesn't make it into your manager the first time (testing out a service).

I also have this case where I'm logged in in one place, but can't reset the email because I don't have the current password. This seems like quite a flaw in accounts design.
