### ISSUE TITLE
Date and hour differ from YouTube to Invidious

### ISSUE THREAD

**Issue by DavidHenryThoreau** [iv-org/invidious#1184]
Date and hour differs between YouTube and Invidous
original post : https://github.com/lekma/plugin.video.invidious/issues/18

**Comment by matthewmcgarvey** [comment]
If you convert the video api's returned published field's unix timestamp to a date time, you'll see that it is exactly 12am GMT. The reason for that is the page we scrape the video info from does not contain a time field, only the date. The channel page, on the other hand, includes the full date time for whatever reason. Neither are wrong, the channel one is just more accurate because that is what we get back from youtube.

video api published field logic https://github.com/iv-org/invidious/blob/1a7e160956dc0ac911dcac33b9231de804bb1924/src/invidious/videos.cr#L518-L520

channel api published field logic https://github.com/iv-org/invidious/blob/1a7e160956dc0ac911dcac33b9231de804bb1924/src/invidious/channels.cr#L80

**Comment by syeopite** [comment]
Fixed by #1797
