### ISSUE TITLE
Videojs buttons on mobile dont work

### ISSUE THREAD

**Issue by ghost** [iv-org/invidious#1239]
I cant change video quality or subtitles on mobile, when i touch the subtitles bar or quality settings nothing happens (all instances) ,only works on computers.

This happens because buttons only work with computer mouse movements. On mobile only buttons turns blue.

![4C687C9D-8D9E-456C-99DD-68F36310F37A](https://user-images.githubusercontent.com/66928292/84610486-bd200900-ae88-11ea-9a22-8c5fdbcb62ff.jpeg)

Im using ios safari (sorry my english)

**Comment by matthewmcgarvey** [comment]
The problem comes from setting `overflow-x: scroll` on mobile screen sizes https://github.com/iv-org/invidious/blob/cce6db4aeb8dd13d4b71fa02595823069afcd331/assets/css/default.css#L305

Without it, the rest of the icons are still hidden but the ones that are shown are clickable. I believe that the best choice would be to remove the overflow property and decrease the font-size at mobile levels to avoid the overflow.

Here is an example with the overflow property removed and font-size decreased
<img width="360" alt="CleanShot 2020-10-13 at 22 12 48@2x" src="https://user-images.githubusercontent.com/17329408/95939262-4563db80-0da1-11eb-8c65-a66f949c7628.png">

It's waaay smaller but it all fits and works as expected.  One way to increase the screen size (which might allow bumping the font-size) is to remove the `h-box` class from the player container https://github.com/iv-org/invidious/blob/cce6db4aeb8dd13d4b71fa02595823069afcd331/src/invidious/views/watch.ecr#L51

**Comment by matthewmcgarvey** [comment]
Just found this pr which, I think, would fix this issue https://github.com/iv-org/invidious/pull/1005

**Comment by TheFrenchGhosty** [comment]
@matthewmcgarvey Yeah I guess it should, it just hasn't been tested yet

**Comment by syeopite** [comment]
Fixed #2008
