### ISSUE TITLE
Subscriptions marked in red

### ISSUE THREAD

**Issue by stemy2** [iv-org/invidious#1267]
Hello,

Sometimes, i have this.
![Screenshot_20200624_070357](https://user-images.githubusercontent.com/22192600/85502999-236b0100-b5d8-11ea-8441-f1df54fccb8a.png)
What does it means exactly ?

**Comment by TheFrenchGhosty** [comment]
According to "guestkato" on Matrix:

the only thing that sets the background color red in default.css or darktheme.css is .deleted, which i guess means the channel has been deleted

**Comment by stemy2** [comment]
Nope, it happens randomly with channels that are absolutly not deleted.

**Comment by TheFrenchGhosty** [comment]
Interesting, I will let the issue open then in case some people know why.

**Comment by LetMeByte** [comment]
Maybe it would help to take a look at how the 'deleted' channels are determined? It might be a simple timeout or some just some error in the corresponding code, or YouTube reporting garbage. I actually noticed the issue just now; seeing it it at least 8 month old, we should do something about it, if we can.

The flagging happened to 3 of 14 channels on my private instance, the red markings are consistent; I just took a look because a new video from one of the channels didn't show up on the frontpage, even after over 4 hours and multiple times of restarting the instance.
The channels are alive and well though, there's no obvious reason for them to be marked as deleted.

Maybe we're picking up something YouTube doesn't want us to? That'd be interesting for sure.

**Comment by SamantazFox** [comment]
@LetMeByte Ah, neat! Could you please provide some details for us to try to reproduce that issue?

- What are the impacted channels?
- Are you using PubSub or the RefreshJob?
- If that's relevant, in which country is your instance located?
etc...

**Comment by LetMeByte** [comment]
- What are the impacted channels?

The affected channels are:
[Incognito Mode](https://www.youtube.com/channel/UC8Q7XEy86Q7T-3kNpNjYgwA) <-- This one is wasn't affected before
[Josh Strife Plays](https://www.youtube.com/channel/UCR9X2tT0_WVfuYO17vqstlA)
[Mental Outlaw](https://www.youtube.com/channel/UC7YOGHUfC1Tb6E4pudI9STA)
[The Hated One](https://www.youtube.com/channel/UCjr2bPAyPV7t35MvcgT3W8Q)


- Are you using PubSub or the RefreshJob?

I have no idea. Knowing that might already be a big step towards the solution, how do I find out? What's the default? How do I change it?


- If that's relevant, in which country is your instance located?

Don't know if it's relevant, I usually use german (VPN) IPs.

Certain videos do not load when connecting via blacklisted (spamhaus) IPs, like official music channels (e.g. VEVO).

**Comment by IronMaltese** [comment]
The hated one and Mental Outlaw had been striked from YouTube in the past, but they aren't anymore, so maybe invidious is checking if the channel has been striked instead of checking if it's deleted

**Comment by LetMeByte** [comment]
That's definitely a possibiliy, I also thought about it having something to do with shadowbanning.

Yet we should take a look at the specific code responsible for parsing the feeds and the data itself.
Due to my lack of knowledge regarding that, I can't do it, though.

**Comment by LetMeByte** [comment]
The problem fixed itself, somehow. YouTube probably adjusted something. Didn't update or anything.

**Comment by SamantazFox** [comment]
> * What are the impacted channels?
> 
> 
> The affected channels are: [SNIP]

Thanks, I'll look into that when I can :)

> I have no idea. Knowing that might already be a big step towards the solution, how do I find out? What's the default? How do I change it?

If you have set a `domain` and `use_pubsub_feeds` to `true`, then you're using PubSub. Otherwise, you're using the `refreshChannelsJob` background job (i.e, pubsub is a system where the youtube servers ping your instance back on update, instead of your instance polling the server. @unixfox please correct me if I'm wrong here).

> Don't know if it's relevant, I usually use german (VPN) IPs.
> 
> Certain videos do not load when connecting via blacklisted (spamhaus) IPs, like official music channels (e.g. VEVO).

Ok, thanks for the info

**Comment by slayernominee** [comment]
i have the same issue with the channels:
the linux experiment, semper video, the morpheus
<img width="1193" alt="Bildschirm­foto 2022-12-30 um 13 30 44" src="https://user-images.githubusercontent.com/64646271/210070439-a1290be3-43d3-48f2-8acd-0e727d2e45c4.png">

**Comment by SwirlyStone5877** [comment]
bump

<img width="1315" height="819" alt="Image" src="https://github.com/user-attachments/assets/e51cbc0b-f7d8-4a50-8da7-544bdd0e9e89" />

all channels in red in the section shown are not deleted

EDIT: oh dear, 3 years ago... oh well

**Comment by unixfox** [comment]
Related to https://github.com/iv-org/invidious/issues/6034

It could be that the RSS feed of the channel stopped working at the moment of the update.

It's tracked in https://github.com/iv-org/invidious/issues/2410 to remove dependency on RSS.
