### ISSUE TITLE
*-topic doesn't play on every instance but invidio.us

### ISSUE THREAD

**Issue by imapotatoalso** [iv-org/invidious#1329]
Salute everyone!
Is there a way to listen to music on invidious?
I run an instance with local=true and it says "video unavailable" plus on the snopyta instance its the same.
The only instance that doesn't have this issue is the main one
https://invidio.us/watch?v=lLV5GVWnVqs
Normally this isn't an issue for me because I just watch music on invidio.us.
Sadly the instance is shutting down on Sept 1st.
How can I enable *-Topic videos on invidious?
I read https://github.com/iv-org/invidious/issues/392 but sadly it didn't help
Thanks in advance!

**Comment by GitWaifu** [comment]
See also #402. As mentioned in #92, YouTube will sometimes still block access to files if they are requested from a different region, even though the videos themselves aren't geo-blocked.

Adding `&local=true` should allow you to view the videos without JS.

_Originally posted by @omarroth in https://github.com/iv-org/invidious/issues/392#issuecomment-471670077_

**Comment by imapotatoalso** [comment]
Is Japan a blacklisted country?
Also some songs on Invidio.us doesn't seem to work anymore: https://invidio.us/watch?v=V4-vEj8uLIQ

**Comment by GitWaifu** [comment]
the specific video you mentioned says it whitelisted almost all countries including Japan and Finland which is allegedly the home of snopyta but Omar says that youtube still blocks the video if it accessed by countries outside of original copyright owner which is most often the USA or Germany. 
Main instance of invidio has multiple servers in major copyright countries and this helps to unblock most of the videos. 
Literally all other forks of invido are based outside of America so all american copyright is blocked for them even from non topic channels that blocked one country and whitelisted all others. 
Today i clicked on 2010 DrDisrespect ad video for a custom Xbox controller and it only played on main instance because it blocked Danish country for copyright music

**Comment by imapotatoalso** [comment]
Ok then :(
Thanks for your help!
