### ISSUE TITLE
Content Security Policy

### ISSUE THREAD

**Issue by DrDRECoder** [iv-org/invidious#1340]
Hello,
I have inserted script to HTML but "Refused to load the script 'https://externalsite.com' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback."

I have tried to insert meta tag in HTML but still get error.
meta http-equiv="Content-Security-Policy" content="Content-Security-Policy: default-src 'self'; script-src 'self' https://externalsite.com 'unsafe-inline' 'unsafe-eval'"

How to fix it?

**Comment by GitWaifu** [comment]
i get the same error messages when invidous blocks its own jpeg thumbnails and player seek preview images - i have no idea if this is connected to your issue in any way

**Comment by afuous** [comment]
It looks like the invidious server is setting the content security policy as an HTTP header, on this line: https://github.com/iv-org/invidious/blob/master/src/invidious.cr#L260. So to change the content security policy, edit this line in the server side code then recompile and restart the server.

**Comment by GitWaifu** [comment]
i get the same policy errors on apple id login iframes on apple's own sites and google blogger comment iframes inside blog posts.
 i believe it is caused by sites trying to gather link referral field data and blocking all requests that send default-src 'self'; script-src 'self'. 
It is common for privacy browsers like Tor to hide referral data to protect users from ad tracking and send default-src 'self'; script-src 'self' instead of website address the user has opened and it seems that invidous is blocking requests with unexpected default-src 'self'; script-src 'self' referral data the same way apple and google blogger do. 
Apple and Google do this to force people to stop using private browsing but it seems rather useless for invidious unless this protects against DDoS and malicious instances that leech server juice from public instances.
Invidious didin't have this default-src 'self'; script-src 'self' policy before Omar announced his departure.

**Comment by SamantazFox** [comment]
> I have inserted script to HTML but "Refused to load the script 'https://externalsite.com' because it violates the following Content Security Policy directive ...

First, why do you want to add HTML or scripts to your instance?

**Comment by SamantazFox** [comment]
Closing, as the OP haven't replied and this can be fixed with Nginx/Apache/Lighttpd/... rules to rewrite the CSP headers.
