### ISSUE TITLE
non-original title for video in english

### ISSUE THREAD

**Issue by rezad1393** [iv-org/invidious#1356]
this youtube video (his whole channel actually) https://www.youtube.com/watch?v=MFCNUvFEVFY has a Japanese title on invidious but a english one on youtube, and it is not a translated one.
also channel name too.
can this be added to invidious?
I know this is not a high priority but maybe add that for later releases?

**Comment by TheFrenchGhosty** [comment]
This is a known issue, sometimes videos will report title in the wrong language in every page (search/channel) except the main video page.

According to omarroth this is a youtube issue and nothing can be done about it.

**Comment by rezad1393** [comment]
> This is a known issue, sometimes videos will report title in the wrong language in every page (search/channel) except the main video page.
> 
> According to omarroth this is a youtube issue and nothing can be done about it.

thanks for adding the tags.
but I didnt get part of your answer.
in youtube the title is in english for all those channel's videos except for when using rss of youtube.
the main video page of video also is in english title (not the title at the toolbar that is in Japanese but the one under video).

but in invidious nowhere anything is in english for this channel (except the video main description which I think is in english from the source (not japanese at all))
not the video title under video, not the channel name.

**Comment by nathgit** [comment]
That's different. I've seen the video title be wrong a few times too, but it's always been in the same language (english).

**Comment by SamantazFox** [comment]
This problem comes from Youtube, there is not much we can do about it.

Basically, content creators have 3 choices:
 - Do not translate video titles
 - Propose their own translations for video titles
 - Opt in for automatic translation of the titles

In the last two cases, the data that youtube returns will contain a translated video title (except on the watch page, for some reason).

The reason why most of the time titles are in english is because this is the locale that invidious uses to fetch data from YT servers (with the `hl=` parameter), as it is the easiest to parse and pretty consistent. However, it has the side effect of always providing english titles when an english version of the title is available.

The only solution so far would be to fetch the `/watch` page for every videos of a playlist or in the search results, as this the only place that (still) provides un-translated titles. But this isn't feasible in reality, as it'll make way too much request to youtube servers, leading to instance being blocked more often and a increase in bandwidth use.

**Comment by TheFrenchGhosty** [comment]
"""""feature"""""
