### ISSUE TITLE
Not relying on any particular instance, but multiple of

### ISSUE THREAD

**Issue by tiotrom** [iv-org/invidious#1369]
This amazing addon https://github.com/SimonBrazell/privacy-redirect randomizes between a list of instances whenever you load a youtube url. It does the same with google maps, instagram, and twitter, for their trade-free alternatives like openstreemaps, bibliogram or nitter. But the invidious instances are the most unreliable from my tests. Instances work 50% of the time or so. How can we check the health of each instance so we pick the best ones from that list, at random?

I think the idea of an extension that pulls at random from a list of instances is the best we can have, since we won't rely on any particular one, but multiple of. Maybe, since you guys are developing invidious, you can help Simon (the developer) to make the extension better. We were talking about detecting when an invidious instance doesn't work in real time (maybe based on the error messages it gives) and quickly picking another random instance.

We talk about the idea here https://github.com/SimonBrazell/privacy-redirect/issues/101

**Comment by elypter** [comment]
the redirect page on invidio.us https://github.com/iv-org/invidious/issues/1321 is supposed to be doing that. maybe imporove on that?

**Comment by tiotrom** [comment]
Wouldn't it be better not to rely on any url? An extension could be much better I'd say. And Simon, who is developing the redirect one, seems very active and willing to improve the extension.

**Comment by arthurrasmusson** [comment]
Instances seem to work pretty unreliably overall. My own instance won't stream video much of the time and often I find others won't either. For example frequently I connect to invidious.snopyta.org and am met with an error message over top of the video frame informing me that video cannot be streamed to my browser because the format is invalid. Strangely enough this seems to affect other instances at random but invidious.snopyta.org most often runs into this I find.
It's seemingly random since if I refresh some amount of the time it just goes away or if I cone back to the page later the error is usually gone.
I'm not sure what would account for this but the consistency of the problem would suggest to me that perhaps relying on multiple instances with various levels of reliability may be a bit premature before a single instance be reliably stream without issue.

**Comment by tiotrom** [comment]
It is true, most of the Invidious instances may or may not work. But randomizing them could be the best solution in the long term so that we don't put the load on any specific one. Also, we could ping these instances via this extension and see which ones are more reliable, and the extension can choose the best one.

**Comment by elypter** [comment]
it would be nice if invidious provided an interface that indicated if it is being rate limited, bandwidth constrained or running against system resource limits.

**Comment by TheFrenchGhosty** [comment]
htttps://invidio.us already do that.

**Comment by tiotrom** [comment]
Would you consider an extension that could handle this automatically?

**Comment by TheFrenchGhosty** [comment]
Privacy Redirect already do that.
