### ISSUE TITLE
Instance invidious.site is using trackers

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#1456]
It could be a good idea to either warn about it on the wiki page, or just completely remove the instance from the list.

Evidence:
![image](https://user-images.githubusercontent.com/52980486/98177689-801de700-1efb-11eb-9426-91ed73cf3cb1.png)

**Comment by TheFrenchGhosty** [comment]
Thank you.

**Comment by wapfalls** [comment]
@SamantazFox and @TheFrenchGhosty thanks for the heads up. Am not well versed with AGPL & GDPR. Since I noticed few youtube proxies on the web using my instance on their applications without permission, and that is adding heavy load on the instace, I thought of checking the traffic sources, and hence added the analytics code.

Now that I understand it violates rules, I have completely removed those codes. You may check for yourself on the source viewer. Let me know if you want me to produce any other evidence.

Thanks!

**Comment by GitWaifu** [comment]
does cloudflare hcaptcha violate anything?

**Comment by Perflyst** [comment]
As long as you dont modify the code without publishing the changes it should be fine. Putting Cloudflare in front is not good for privacy but it doesnt violate any license

**Comment by TheFrenchGhosty** [comment]
@wapfalls 

>Am not well versed with AGPL & GDPR.

AGPL require any modification that is done on a software not used by private use, to be also open source with a proper explanation of the change. You didn't do that and kept the modification closed source, without any explanation for users.

GDPR require adding the ability for users to opt-in to the analytics or at least to be able to opt-out. You didn't do that, and the analytics was enforced.

>Since I noticed few youtube proxies on the web using my instance on their applications without permission, and that is adding heavy load on the instance, I thought of checking the traffic sources, and hence added the analytics code.

This is a problem on every single instance. You are behind cloudflare so it shouldn't be a problem for you. To check the traffic source: Cloudflare should have everything for you, or your Nginx (or whatever reverse proxy you use) logs.

>You may check for yourself on the source viewer. Let me know if you want me to produce any other evidence.

Checked seems clean. Instance re-added.

PS: Update your instance, you don't have the fix for the broken channels.

**Comment by wapfalls** [comment]
Thanks @TheFrenchGhosty 

Will update the instance for the fix.
