### ISSUE TITLE
Include title of video in URL

### ISSUE THREAD

**Issue by raphaeljolivet** [iv-org/invidious#1483]
URLs should be designed as user / human interface.
I have always been surprised that YouTube URLs do not tell anything about what you are going to see. 
One should support titles included in URLs like articles for journals do.

Proposal : a conservative approach, being backward compatible with previous URLs, adding an optional title part.

Here is a proposal 👍 
* `domain.tld/watch?v=XXXXXX` (still supported)
* `domain.tld/v/XXXXXXX/ricky-astley-never-gona-give-you-up` (shown by default, title is checked to be valid)

The title could be truncated to keep reasonable URL length

**Comment by demostanis** [comment]
How would we rick roll people?

**Comment by TheFrenchGhosty** [comment]
Pretty cool idea.

**Comment by arrowgent** [comment]
cool idea, would be very useful
also goes against the idea of "link shorteners" which try to reduce letters so "large" datasets load faster.

but if this were created then also make:
```
domain.tld/v/XXXXXXX/
```
a shortcut that still works


another problem is a TON of videos use titles which are unicode instead of standard UTF-8/ISO-8859 encoding
so the syntax would have to ___ blank or 0 those letters in a title
because lets be real, no one wants to see a url with &%2F style reformatting spammed a hundred times when characters are replaced

**Comment by raphaeljolivet** [comment]
Glad you like it !
I agree for the encoding (even if modern browsers can deal with it almost transparently) :
URLs are human interfaces and should be designed as such.

**Comment by nathgit** [comment]
I can see your point, but that would result in a ridiculously long url sometimes.

**Comment by TheFrenchGhosty** [comment]
@nathgit So? It's would be optional.

**Comment by SamantazFox** [comment]
Problem would be that it only works for english titles.

For instance, here is what a japanese title would look like:
```
domain.tld/v/N-xVBVsDSxE/%E3%80%90%E3%83%95%E3%82%A9%E3%83%BC%E3%83%88%E3%83%8A%E3%82%A4%E3%83%88%E3%80%912022%E5%B9%B42%E6%9C%888%E6%97%A5+%E4%BB%8A%E6%97%A5%E3%81%AE%E3%82%A2%E3%82%A4%E3%83%86%E3%83%A0%E3%82%B7%E3%83%A7%E3%83%83%E3%83%97%E3%80%90Fortnite%E3%80%91
```

**Comment by unixfox** [comment]
Closing as unfortunately it's not a practical idea. This would also break the link compatibility with youtube links.
