### ISSUE TITLE
Yewtu.be isn't displaying some channels

### ISSUE THREAD

**Issue by Coaggly** [iv-org/invidious#1493]
I'm not sure if I should put this issue here, but when I clicked the github link on yewtu.be it linked me here.

Ex Channel A displays. Channel B loads, but displays "Could not get channel info."

**Comment by tirz** [comment]
May be fixed by https://github.com/iv-org/invidious/pull/1490 (merged 10 minutes ago).
Before that, `channels.cr` was using a custom parser.

Can you retry on this instance: https://vid.encryptionin.space/ ?
It is up since today with the https://github.com/iv-org/invidious/pull/1490 path (not sure if it will stay up).

**Comment by hackerncoder** [comment]
It'll stay up.

**Comment by Coaggly** [comment]
Yewtube is still not displaying some channels. vid.encrpyitionin.space is saying 'Read timed out ', yewtube is saying ' Nil assertion failed '.

> May be fixed by #1490 (merged 10 minutes ago).
> Before that, `channels.cr` was using a custom parser.
> 
> Can you retry on this instance: https://vid.encryptionin.space/ ?
> It is up since today with the #1490 patch (not sure if it will stay up).
