### ISSUE TITLE
Legality issues.

### ISSUE THREAD

**Issue by hackerncoder** [iv-org/invidious#1501]
Hello!

I was forced to take down my instance today because of disputes about the legality of running one.  
Could anyone provide me with something so that I can prove it is legal to do so (in Denmark).

There was a problem with the fact that the software proxies images, text and other content from YouTube through itself, however I am having trouble remembering what the exact problem was.

I have tried looking at older Issues and found #130, but it doesn't answer my question.

Thanks.

**Comment by Perflyst** [comment]
Can you forward the abuse message / DCMA takedown request? Why did you need to take it down?

**Comment by hackerncoder** [comment]
@Perflyst I have not received anything, I am just worried about the legality.

**Comment by llacb47** [comment]
You said:

>I was forced to take down my instance today because of disputes about the legality of running one.

Then you said:

>I have not received anything.

Which is it?

**Comment by hackerncoder** [comment]
Both? Someone forced me to take it down. I ran it on a server I did not pay for, and they were concerned about the legality and then forced me to take it down.

**Comment by RandomErrorMessage** [comment]
No one can ever prove it's legal without going to court and establishing precedence in your jurisdiction. The best you can do is a hire a lawyer to give you his opinion, which is just an opinion. In my opinion the risk is low and if there is an issue it will likely result in a cease and desist at which point you'll have to decide if it's something you want to fight.

I know that internet law in the EU is rather draconian and speech is restricted, for this reason it's often the best to host inside the US to take advantage of it's strong free speech laws and section 230 which immunizes you against the actions of your users. Frankly I would be more worried about criminal complaints from your own government rather than civil complaints from corporations. The obvious example of this is giving Germans the ability to circumvent their censorship laws which YouTube's site does enforce (and invidious doesn't).

I am not a lawyer. I don't know Danish law.

**Comment by TheFrenchGhosty** [comment]
It's as legal as a proxy. The only difference is that Invidious also has a custom frontend.
