### ISSUE TITLE
Subscriptions feed no longer updates

### ISSUE THREAD

**Issue by boogsnaxx** [iv-org/invidious#1541]
Version: `-20d2d14 @ master` (yewtu.be)

Newest videos in subscription feed are 6 days old, no new videos are added when refreshing page and no new unseen notifications are displayed.

**Comment by TheFrenchGhosty** [comment]
@unixfox Do you have cronjobs that restart the instance setup on yewtu.be?

**Comment by unixfox** [comment]
Well it restarts Invidious yes but it worked great for 3 months with the same cronjobs, so I don't really know what happen.

**Comment by unixfox** [comment]
@TheFrenchGhosty you can close this issue because the subscription feed just unstuck by itself. I really don't know what happened. Gotta love Invidious bugs!

**Comment by TheFrenchGhosty** [comment]
@unixfox Nice, indeed, those bugs are trully amazing.

**Comment by lucky13820** [comment]
I’m having the same issue on my personal instance, 2020.12.13-a291b29. I just installed yesterday everything worked fine yesterday, but now it won’t update the newest videos. The latest is 8 hours ago. And there are should be at least 10 new videos during this period.

**Comment by lucky13820** [comment]
Restart invidious seems fixed the problem. Does that mean I have to restart invidious every time I encounter this problem?

**Comment by TheFrenchGhosty** [comment]
@lucky13820 Invidious needs to be restarted every 1-3 hours to work correctly.

**Comment by imiric** [comment]
@TheFrenchGhosty Is that an official stance from the core team? If so, it should be mentioned in the `README` and the usage documentation, unless I missed it.

Frankly it's awful UX to have to restart the service every 1-3 hours. I can't imagine the requirements for not being able to restart whatever process it needs internally, rather than offloading this maintenance to the user.

If nothing else, couldn't there be a simple "update" button in the web UI that refreshes the subscriptions on demand? I'd rather have the option to update subscriptions manually than the current broken auto-updater.

Apologies if I'm being too demanding. I love this software and appreciate the maintenance work the community picked up after the original author left. I would try to fix these issues myself if it were written in a more mainstream language, though I might look into Crystal if I'm bored over the holiday break. :) Happy New Year!

**Comment by TheFrenchGhosty** [comment]
@imiric 

>Is that an official stance from the core team?

I guess? It's basically what we tell everyone to do. We'll indeed have to edit the readme.

>Frankly it's awful UX to have to restart the service every 1-3 hours. I can't imagine the requirements for not being able to restart whatever process it needs internally, rather than offloading this maintenance to the user.

We don't have any fix, and none of the people sending PRs have found a solution. Feel free to open a PR if you know how to fix this.

>If nothing else, couldn't there be a simple "update" button in the web UI that refreshes the subscriptions on demand? I'd rather have the option to update subscriptions manually than the current broken auto-updater.

Sure, PR?

>Apologies if I'm being too demanding. I love this software and appreciate the maintenance work the community picked up after the original author left.

You're not the first one asking stuff... we just aren't able to work on it directly, and the people that do work on it have already fixed dozens of bugs.
