### ISSUE TITLE
Community - display post comments

### ISSUE THREAD

**Issue by B0pol** [iv-org/invidious#1614]
Example: https://www.youtube.com/post/UgwmeTG6n1iDK6NNupJ4AaABCQ

On youtube you can click on the image or the comment button to access comments

**Comment by B0pol** [comment]
still relevant and applicable

**Comment by AHOHNMYC** [comment]
We have [community.js](https://github.com/iv-org/invidious/blob/master/assets/js/community.js) for loading comments, but it is doesn't work, because server side doesn't create blocks for loading responses.
Whole community page designed as comments page authored by channel. Comments (which in fact are replies to main comment) have to be displayed by this code:
https://github.com/iv-org/invidious/blob/4c1a5f84fa3310a2d2d6752d4bc8d42580c9baa0/src/invidious/comments.cr#L440-L451
