### ISSUE TITLE
Store anti captcha cookies in database

### ISSUE THREAD

**Issue by Perflyst** [iv-org/invidious#1628]
The `GOOGLE_ABUSE_EXEMPTION` cookie from anti-captcha.com is currently stored in the config file.

This is problematic in multiple ways:
1. You cannot mount the config file in a container with "ro" flags
2. Invidious can kill itself completely if it crashes during writing the config file (the config is empty afterwards)
3. Multiple Invidious processes on the same machine create new anti-captcha cookies (costs more money)

The anti-captcha cookie contains an IP address. If Invidious is running on multiple servers with different IPs but using the same database there should be a row for each IP in the database table.

**Comment by unixfox** [comment]
Some notes about this:
The developer that implements this functionality should add a lock functionality for the anti-captcha system because if multiple processes of Invidious are running at the same time and try to write in the same "cookies" entry at the same time then this will cause some issues.

Ideally a simple lock system like this is the best:
One Invidious process lock the "cookies" entry in the database then the other ones won't try to solve, once the process that solved the captcha finds new cookies then it stores them in the database and the other processes use these new cookies.
A lock timeout should also exist in case the process that was trying to solve the captcha crash in the middle of trying to solve the captcha.

**Comment by unixfox** [comment]
> I think this new way of storing the captcha cookie that it is already implemented, stopped working and entire instances are not functioning anymore. Our ytb.trom.tf and these other instances that I suspect are dealing with the same issue:  https://invidious.snopyta.org https://vid.puffyan.us https://invidious.namazso.eu  - they output "video unavailable". If I am to delete the cookie line from the config file, it will work for a bit. The it stops once it generates that cookie line in the config. This stopped working some 2 days ago suddenly.
> 
> The logs do not show much. https://paste.trom.tf/otodipoles.pl
> 
> And stuff like
> 
> ```
> 2021-08-10 01:25:00 UTC [error] get_video: mepxSzKfEhQ : Video unavailable.
> 2021-08-10 01:25:02 UTC [error] get_video: hW-vd2nQxqA : Video unavailable.
> 2021-08-10 01:25:20 UTC [error] get_video: VunlzEHdMGY : Video unavailable.
> 2021-08-10 01:25:32 UTC [error] get_video: eMudLfL76Sg : Video unavailable.
> 2021-08-10 01:25:37 UTC [error] UpdateDecryptFunctionJob : Nil assertion failed
> [development] Kemal is ready to lead at http://0.0.0.0:3000
> ```
> 

This has nothing to do with this issue. This issue is about storing the fetched Google Captcha cookies in the database instead of a file.
Open another issue.

**Comment by unixfox** [comment]
We don't need anticaptcha anymore, closing that until we need it again.
