### ISSUE TITLE
Rate limiting restrictions on captions endpoint

### ISSUE THREAD

**Issue by krackers** [iv-org/invidious#1703]
On all of the instances captions no longer work. Though the different languages are correctly available in the menu, selecting them does not display the captions.

Looking at the API call to `api/v1/captions/qQD98_HFT68?label=English&hl=en-US` the output is

```
<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We're sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can't process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>
```

While this would ordinarily make me think that it is a server-specific issue, the issue seems to be present across all the instances available.

**Comment by tenpura-shrimp** [comment]
Looks to me like it's still an ipban.  On my instances some are working and some are blocked.  Running the server locally also isn't blocked.

Now the question is, why did all the all of the instances get ipbanned for specifically the captions endpoint?  I have some hypoteses:
1. This is not enabled by default in youtube, so the request limit on this api may be lower.  The invidious code sends an http request for all of the captions automatically regardless of whether or not they are enabled, which is high qps.
2. The vtt format is not used for youtube web, so this could be restricted to lower requests.

Either way, I expect that changing the codes so that they don't always fetch the captions for every video might help.

**Comment by tenpura-shrimp** [comment]
We can try using this flag in videojs
```
videojs(element, {
  html5: {
    preloadTextTracks: false
  }
};
```
https://github.com/videojs/video.js/commit/0e37fbf02c8dee1d01bfc69b0a718d605b423cc5
