### ISSUE TITLE
[Bug] Next page button is missing

### ISSUE THREAD

**Issue by lunainvictum** [iv-org/invidious#1708]
tldr The next page button is missing and you can't view more than 19 videos through the search page.

------

Hi,

if i search for "speedrun", i get only 19 Results. On Youtube millions of Results. 

This Problem occurs on every instance. And every instance delivers the same 19 Videos. 

And another Problem is, if Invidious thinks there is more, the next page shows the same videos from the first page. And on the third, fourth, and so on. 

Sry for my bad english. im native german.

**Comment by hackerncoder** [comment]
This appears to be a duplicate of #1480. If so, please comment on the appropriate existing issue instead. If you believe this is not really a duplicate, please leave a comment briefly explaining why. Thank you.

**Comment by lunainvictum** [comment]
The Secound Problem seems to be a duplicate.

But the first one not. It is only possible to find 19 Videos (the same, unique ones) on every instance.

**Comment by TheFrenchGhosty** [comment]
A 20$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 20$ (in BTC) from the Invidious project.

More details: https://github.com/iv-org/invidious/issues/1898

**Comment by ralf1307** [comment]
Is this fixed by adding "Next Page" and "Previous Page" buttons on the first page or am I misunderstanding the issue? As adding &page=2 results in going to the next page with the buttons shown (with different results from the first page of course).

**Comment by tagener-noisu** [comment]
The problem is that the search view only shows the next page button if the number of videos is greater than 19, but the search sometimes returns just 19 videos instead of 20. What's more interesting, the number of results doesn't depend on the search query, if you search for "games" for example and then reload page several times, you can see that sometimes the next page button is present and sometimes not.
I'm not sure if the problem is with the youtube API, or processing of the results inside invidious. Is there a way to see the raw youtube search results through the API?
