### ISSUE TITLE
[Bug] thumbnails url are not proxied

### ISSUE THREAD

**Issue by B0pol** [iv-org/invidious#1792]
**Describe the bug**

In thumbnails array, the first item has a different host than the other

e.g. 
https://invidious.snopyta.org/api/v1/search?q=musique&type=all
```json
"videoThumbnails": [
      {
        "quality": "maxres",
        "url": "https://invidious.snopyta.org/vi/ioJx1Y-UbdA/maxres.jpg",
        "width": 1280,
        "height": 720
      },
      {
        "quality": "maxresdefault",
        "url": "https://i.ytimg.com/vi/ioJx1Y-UbdA/maxresdefault.jpg",
        "width": 1280,
        "height": 720
      },
      {
        "quality": "sddefault",
        "url": "https://i.ytimg.com/vi/ioJx1Y-UbdA/sddefault.jpg",
        "width": 640,
        "height": 480
      },
      {
        "quality": "high",
        "url": "https://i.ytimg.com/vi/ioJx1Y-UbdA/hqdefault.jpg",
        "width": 480,
        "height": 360
      },
      {
        "quality": "medium",
        "url": "https://i.ytimg.com/vi/ioJx1Y-UbdA/mqdefault.jpg",
        "width": 320,
        "height": 180
      },
      {
        "quality": "default",
        "url": "https://i.ytimg.com/vi/ioJx1Y-UbdA/default.jpg",
        "width": 120,
        "height": 90
      },
      {
        "quality": "start",
        "url": "https://i.ytimg.com/vi/ioJx1Y-UbdA/1.jpg",
        "width": 120,
        "height": 90
      },
      {
        "quality": "middle",
        "url": "https://i.ytimg.com/vi/ioJx1Y-UbdA/2.jpg",
        "width": 120,
        "height": 90
      },
      {
        "quality": "end",
        "url": "https://i.ytimg.com/vi/ioJx1Y-UbdA/3.jpg",
        "width": 120,
        "height": 90
      }
    ]
```

On snopyta it's not a problem but using another instance it is, e.g. invidious.zee.li

the URL becomes https://invidious.zee.li:3000/vi/mtX6tnewbgg/maxres.jpg and it's not available.

**Steps to Reproduce**
Do any query to API related to video thumbnails, e.g. /api/v1/search?q=musique

**Logs**

**Screenshots**

**Additional context**

**Comment by B0pol** [comment]
By looking at the source code it is expected

https://github.com/iv-org/invidious/blob/2dcfec263950116b94f7d1599d294207ae218d70/src/invidious/videos.cr#L1150-L1162

then the issue is probably with invidious.zee. [@meZee](https://github.com/meZee) could you share your configuration file?

**Comment by TheFrenchGhosty** [comment]
I'm guessinf invidious.zee doesn't have the external port setup.

**Comment by appletalk** [comment]
I ran into what I think is the same issue with my docker instance.  The external port does not need to be setup if you include a correct value for `external_port: 443` in the config.  Port 3000 is *not* required to be forwarded for a correctly functioning instance, it is only used as a default when one is not specified.
This config entry changes the client requests to use port 443 which functions through the reverse proxy, rather than the default of 3000 which likely will not be port forwarded.

In my case this went in the docker-compose.yml under environment variables but I assume there is a related location (config.yml ?) for non-docker based installs.

Without this port setup, several client requests get created as invidious.example.com:3000 which is incorrect when using a reverse proxy.  Traefik in my case, but should be an identical problem with nginx/apache.

What appears to be happening is that while most of the client requests for invidious are proxied as normal.  Video playback and general use of the instance will appear to be working.  However additional requests for thumbnails, link preview images for shared urls, and thumbnails previews when dragging across a video timeline end up broken.


It would be useful to add this `external_port: 443` information should be added to the install guides, as I went in circles for some time before identifying the problem.
I hope this helps!
