### ISSUE TITLE
Increase frequency of subscription updates?

### ISSUE THREAD

**Issue by winteriscariot** [iv-org/invidious#1823]
I've noticed that on my self-hosted instance of Invidious my subscription feed is several hours behind youtube. like currently, the most recent video on my sub feed is 4 hours old, while if I go look at the actual youtube channels they've since released videos.

since i'm the only one using this instance, is it possible to increase the frequency at which invidious looks for new videos?

**Comment by TheFrenchGhosty** [comment]
https://github.com/iv-org/invidious/issues/1541

**Comment by unixfox** [comment]
This is partially due to the fact that some part of the code of Invidious just stop working and require a restart of the process in order to have it functioning properly again.
But you can also speed up the process of refreshing the subscription update by incrementing `channel_threads`.

Also, if you want near instant subscription update then enable `use_pubsub_feeds` and set `domain:` to the domain where you Invidious is exposed. Don't forget to set `external_port` to `443` if you are using HTTPS.
