### ISSUE TITLE
[Feature request] Add UI button redirect to a healthier instance when watching a video on a particular instance

### ISSUE THREAD

**Issue by jgarte** [iv-org/invidious#1873]
**Is your feature request related to a problem? 

It'd be great if there were a button or drop down menu to select another public instance.

**Describe the solution you'd like**

For example,

For example, I would like to have a button on the interface for the video link below so I can choose a different instance if the snoypta instance is not cutting it that day for whatever reason:

https://invidious.snopyta.org/watch?v=2s9fM0CDAQ4

**Comment by syeopite** [comment]
Something like this? 
<img src="https://user-images.githubusercontent.com/70992037/112706886-1ea4e780-8e9f-11eb-85ec-60ee22d14778.png" width="305" height="376">  <img src="https://user-images.githubusercontent.com/70992037/112706937-83f8d880-8e9f-11eb-8e06-d6bb54af7f6d.png" width="352" height="521">

I've added a hyperlink on my local branch that redirects to a random instance. However, since it requests instances from invidious.io it may increase the load on that by quite a bit.
