### ISSUE TITLE
DASH video corruption seemingly at random

### ISSUE THREAD

**Issue by Discookie** [iv-org/invidious#193]
I've been watching DASH videos, and this is the second time I've had a corrupted video like this one.

![image](https://user-images.githubusercontent.com/16914176/46250494-096cb080-c43c-11e8-8c66-b19587341506.png)

There's sometimes a full-screen color change, but otherwise only the top few rows change.

![image](https://user-images.githubusercontent.com/16914176/46250506-42a52080-c43c-11e8-9fdd-798c3a03473d.png)

It looks like the video files are somehow misaligned? It might come from proxying dropping a bit of data, or from a bug in the DASH player. A refresh fixes it, and usually after a minute or so it fixes itself.

I couldn't find a way to reproduce this issue reliably, but here's the link anyways:
https://invidio.us/watch?v=-LytcXun4hU

I've had this issue on 2 separate machines, on Waterfox 56.2.3 on Win10/AMD and a Chromium 69.0 on Win8.1/Nvidia.

**Comment by omarroth** [comment]
Does it reliably happen ~x seconds into the video? It might be the case that Invidious is generating a bad manifest that results in an incorrect offset like what appears to be encountered. Does devtools show any errors?

Currently, Invidious uses [videojs/videojs-contrib-dash](https://github.com/videojs/videojs-contrib-dash), because [videojs/http-streaming](https://github.com/videojs/http-streaming) does not yet support features that Invidious uses in its manifests. I suspect the issue is in the player since it disappears after a refresh, and I think this issue will likely go away after switching to http-streaming.

**Comment by Discookie** [comment]
Found a semi-reliable way to reproduce it:
Simply jump forward with the arrows to the very end of the buffer.
If you get unlucky, your video will corrupt the same way.

dash.mediaplayer.min.js throws this warning:
```
[496953][Stream] onBufferingCompleted - can't trigger STREAM_BUFFERING_COMPLETED because streamProcessor audio is not buffering completed
```
The audio and the corrupted video continued without interruption.

A potential fix would be to stop the video and wait for buffer ~1s before the end of the buffer?

**Comment by omarroth** [comment]
Switched over to http-streaming with 811d11062d29786aefed09ab991c9deb88675a23 which should hopefully resolve this issue.

**Comment by Discookie** [comment]
Encountered it the very first time I tried to switch resolutions with the new source selector :/

Although it's starting to smell more like hardware issues, because Streamable's being corrupted on the AMD machine too. GPU/decode stress testing didn't report anything so far, but I'll keep testing.
