### ISSUE TITLE
[Bug] Videos with 1 million views are shown as singular - view

### ISSUE THREAD

**Issue by thansk** [iv-org/invidious#1946]
**Describe the bug**
Next to videos (in the related section and the search results) there is an indicator showing the views, I saw a video having ~1M views and it was showing as "view" instead of "views" I assume the letter isn't accounted for. Videos with 1.1M show up correctly as "views"

**Steps to Reproduce**
1. Find a video that has ~1M views

**Comment by SamantazFox** [comment]
The problem is due to the way translation files are made. Currently, the number of videos is matched against a regex, in every single translation file. The problem is way larger and even more complex for other languages.

Check out this comment for more details: https://github.com/iv-org/invidious/pull/1920#issuecomment-808952921
