### ISSUE TITLE
[Bug] Music videos won't play

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#1947]
**Describe the bug**

Lately every music video I have tried to play including some fan recorded footage from concerts refuses to play. Instead of playing there is a small 'x' in the center of the video with the following text at the top:

"The media could not be loaded, either because the server or network failed or because the format is not supported". 

There are other videos that don't play too but they're not specific types of videos.

**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by SamantazFox** [comment]
This is due to the copyright enforcement that youtube does on such videos. If you can't watch the video in "embedded" mode either, that's definitely it (to open in "embedded" mode, click on "embed" near the "watch on youtube" link, below the video).

Afaik, invidious doesn't have the required workarounds for this. [youtube-dl](https://github.com/ytdl-org/youtube-dl) does, so you can use this to download the video and listen to the song. NB: such copyright bypass code is what caused the DMCA request against youtube-dl, so I may understand why the original author, and the current maintainers of invidious don't want to implement them.

**Comment by tenpura-shrimp** [comment]
does it still happen with proxy and/or dash enabled?

Please give examples.

**Comment by nathgit** [comment]
@SamantazFox I figured that was what it was, with music videos, although it does happen occasionally on non music videos. @tenpura-shrimp I don't remember enabling it, so I assume it's default but proxy is enabled. Dash just says auto.

**Comment by austinhuang0131** [comment]
@nathgit This happens on (effectively) any videos that has any of the following on the left sidebar:

* "License:" a list of license holders
* "Blacklisted Regions" country codes
* "Whitelisted Regions" country codes

So if it embeds a copyrighted content, the video will have these restrictions. So pretty sure it works as expected

**Comment by tenpura-shrimp** [comment]
I tried several videos that have "License" and it works fine with dash/proxy enabled, but it won't play without dash/proxy.  Youtube is probably enforcing some ip stuff in the cryptogram thingys so you will need to proxy.

@nathgit you need to set preferred quality to dash.

**Comment by SamantazFox** [comment]
> I tried several videos that have "License" and it works fine with dash/proxy enabled, but it won't play without dash/proxy. Youtube is probably enforcing some ip stuff in the cryptogram thingys so you will need to proxy.

Apparently, it's because YT is geo-blocking requests. So if the request for the video stream doesn't come from the same IP which requested the URL (i.e "dash" and "proxy video" are not used), then YT gives a 403 error, resulting in the player error we see.

Try to use DASH quality (as it will always be proxied through the instance).

**Comment by unixfox** [comment]
Closing in favor of https://github.com/iv-org/invidious/issues/602 and https://github.com/iv-org/invidious/issues/2850

This issue is likely going to be somewhat fixed in https://github.com/iv-org/invidious/pull/3011

Please also read about this issue in the documentation: https://github.com/iv-org/documentation/blob/master/docs/faq.md#q-the-media-could-not-be-loaded
