### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#195]
Please consider to add support of browser-based notifications about new videos published at subscribed channels, like YouTube does when you click on the 'Bell' button.

**Comment by omarroth** [comment]
Are there any good or recommended options for creating a modal similar to the notification modal provided by YouTube?

**Comment by dimqua** [comment]
Well, the only thing I need is to be able to recieve notifications about new videos directly to my web browser on desktop, even if Invidious website is not open.

**Comment by dimqua** [comment]
Ohh, it has already been implemented recently. Good job!

**Comment by omarroth** [comment]
I think I misunderstood the original issue. I was assuming the feature request was for something like this:

![image](https://user-images.githubusercontent.com/14208607/58773092-67c8d080-8581-11e9-9739-dd49f96ce798.png)

I'm not quite sure which parts are missing since I'm a bit confused on what's being requested. Currently notifications are provided in the subscription feed as part of regular uploads, and support for [system notifications](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API) is being tracked in #502, for example:

![Notification](https://user-images.githubusercontent.com/14208607/58773288-1c62f200-8582-11e9-8658-1dec5c383676.png)

If you think this has already been implemented then it makes sense to close this, otherwise would you mind providing a little clarification for the requested functionality?
