### ISSUE TITLE
Are instances getting less and less functional over time?

### ISSUE THREAD

**Issue by TROMsite** [iv-org/invidious#1970]
We have this instance for just a few weeks now - https://ytb.trom.tf/
It worked so well at first: search worked, pulling comments and descriptions for videos worked and so forth. Now it only works to see individual videos, despite us doing nothing to the instance. So, is it possible that parts of it got blocked by youtube?

**Comment by nathgit** [comment]
It may be being blocked by youtube. No videos seem to be playing for me on every instance I've tried. Most of them don't even show the video object. It just shows the error: "Could not extract video info. Instance is likely blocked.
". I even got an error message at first when I tried to export data thinking maybe it was time to switch to another instance, but the third time I tried it, it finally worked. I'm kind of thinking .:thinking::question: maybe it was a 503 error, but I don't remember for sure. I have had individual videos refuse to play occasionally, but not every video on every instance.

**Comment by unixfox** [comment]
Invidious rely on unstable HTML code from YouTube, when I mean unstable is that YouTube can change this HTML code without any notice and thus this break Invidious.

That's why we often have ["youtube changed" type issues](https://github.com/iv-org/invidious/issues?q=is%3Aissue+sort%3Aupdated-desc+label%3Atype%3Ayoutube-change+is%3Aclosed). The contributors of Invidious try to fix those issues as soon as possible and then publish new commits on the GitHub of Invidious.

Then once the fix is published we expect every user running Invidious need to update their instance but if you don't update it then the instance will still won't work with the part that broke. In this case it seems like your instance is not up to date because I can errors like "this channel doesn't exist": https://ytb.trom.tf/channel/UCLVVBWrp9jw4-SYUoU42hcg

So the tldr is to keep your instance updated.

**Comment by TROMsite** [comment]
@unixfox That makes sense! Thank you for the explanation! Unfortunately I am using a Yunohost install so it all depends on how often they update their packages. But at least I now know why these things happen. Thanks again!
