### ISSUE TITLE
Why does DASH proxy through the server?

### ISSUE THREAD

**Issue by Latrolage** [iv-org/invidious#2026]
Just a query...
Tthe documentation says 
"DASH is a streaming technique used by YouTube to provide resolutions higher than 720p by providing multiple files for a client to use depending on network and user preferences."

Is DASH a client or server side thing? If it's server side, why can't the client stream directly through the Youtube servers without proxying through the invidious instance? And if it's client side, then why can't it be implemented by the invidious front end?

Above that line, it also says this "This is because the audio and video streams are separated and Invidious currently can't sync them together." Is it because there isn't a known way to do it yet, or that it's just not been done yet?

Sorry, I don't understand the system that much.

**Comment by unixfox** [comment]
@FireMasterK maybe you have some knowledge to share about this

**Comment by FireMasterK** [comment]
Yep, this is because you would get CORS errors otherwise since YouTube doesn't like requests with an `OPTIONS` method (It returns an error).

> Is DASH a client or server side thing? If it's server side, why can't the client stream directly through the Youtube servers without proxying through the invidious instance? And if it's client side, then why can't it be implemented by the invidious front end?

This is because of how CORS and YouTube's servers work, if you use an external player such as VLC, it would work without the need of proxying.

> Is it because there isn't a known way to do it yet, or that it's just not been done yet?

DASH is the best way to solve this issue, I spent looking for a solution for this and ended up at DASH again.

However, there is good news, if you're daring enough to write an extension, you could perhaps implement DASH without the need of proxying!

**Comment by syeopite** [comment]
Closing as it looks like the question has been answered.
