### ISSUE TITLE
Playlist RSS feed only displays the first 16 entries even if there are hundreds

### ISSUE THREAD

**Issue by manoflinux** [iv-org/invidious#2034]
**Describe the bug**
[Bug] when viewing the rss feed for a playlist it only displays the first 16 entries even if there are hundreds.

**Steps to Reproduce**
find a playlist list like this one with more than 16 entries, this one has over 300. 
https://invidio.us/feed/playlist/PLEYB_9ISPPXHtD6XR_gxvqNSeGdLKhyae
Click on the rss feed and look at the number of entries in the resulting xml. 

Whats strange is it looks like the max number for subscriptions is higher at 40 and if I change it in the settings to make it 999 I get over a thousand responses for subscriptions, but for playlists still only 16. 
 
**Logs**
no errors in the logs. 

**Screenshots**

**Additional context**
being able to get the whole list as rss instead of just the top few would be very helpful, any suggestions including manually patching the code would be appreciated. 
Just tell me what line to change.

**Comment by SamantazFox** [comment]
Afact, RSS feeds are meant to provide updates, not whole playlists nor complete blogs. So what you usually get are the latest 10 to 20 blog posts entries or items.

As for the code, the line you want is here:
https://github.com/iv-org/invidious/blob/bfd02ac13dd79dad88316a36d3d93478eb70290f/src/invidious.cr#L1405

What the current implementation does is simply downloading the feed from youtube, parse the XML, and create an XML file with all links replaced, so your RSS client will ping the invidious instance instead of youtube.

If you want to have longer RSS feeds, you'd need to implement a system that will get all of the videos from a playlist (this can be dozens of requests to the youtube API) and then create a giant RSS feed file from that data.

**Comment by manoflinux** [comment]
ah, thanks, so the only rss feeds you actually build are for the subscription page, the rest you just grab from youtube. It makes sense, for most people it would work just fine that way.
