### ISSUE TITLE
[Bug] Videos are still able to show up in the Popular feed with registration and login disabled 

### ISSUE THREAD

**Issue by Eggo-Plant** [iv-org/invidious#2100]
When I created my invidious instance, I made a single account and subscribed to a few channels that I wanted to appear on the home page. I then disabled registration and login because I didn't want anyone to be able to change the channels that appeared on the main page. 
However, after checking back on it today, there seems to be a lot of activity and a fairly large increase in disk space from the postgres database. I checked the home page, and there are a ton of channels that weren't originally there. I was under the impression that only channels that were subscribed to would show up on the main page.
The VPS that I use to host Invidious has very limited disk space, and this morning I was actually unable to access the site because there was not enough disk space left over. This is concerning, and I won't be able to host an Invidious instance if I can't block people from subscribing to channels.

**Comment by SamantazFox** [comment]
> I made a single account and subscribed to a few channels that I wanted to appear on the home page. I then disabled registration and login because I didn't want anyone to be able to change the channels that appeared on the main page.

Can you please describe what you mean by "the home page"? Are you using the default settings (the "Popular" feed)?

If you have set the default home page to either "Popular" or "Trending", you can't choose what will go on those tabs. They're made by Youtube, based on different criteras that we can't control.

> However, after checking back on it today, there seems to be a lot of activity and a fairly large increase in disk space from the postgres database.

The database is used, in addition to user management, as a data cache. Things like playlists, channel infos, video infos, etc... are stored on it. We are aware that this is not the best way of doing caching, so for now you have to follow the [database maintenance documentation](https://github.com/iv-org/documentation/blob/master/Database-Information-and-Maintenance.md) in order to limit database growth.

> I was under the impression that only channels that were subscribed to would show up on the main page.

If you have set the default home page to either "Subscriptions" or "Playlists", then yes, you will only see the content you subscribed to. But you have to be logged in to see them. So if you disabled login, you will never see your personalized subscription feed.

> The VPS that I use to host Invidious has very limited disk space, and this morning I was actually unable to access the site because there was not enough disk space left over. This is concerning, and I won't be able to host an Invidious instance if I can't block people from subscribing to channels.

If you really don't want other people to use your instance, you should put it behind a simple password protection (it's called [HTTP authentication](https://en.wikipedia.org/wiki/Basic_access_authentication)', any web server can do it)

**Comment by syeopite** [comment]
> If you have set the default home page to either "Popular" or "Trending", you can't choose what will go on those tabs. They're made by Youtube, based on different criteras that we can't control.

The popular page is entirely generated by Invidious based on what the users of that instance watch.

**Comment by SamantazFox** [comment]
> The popular page is entirely generated by Invidious based on what the users of that instance watch.

OOOhhh, right! My bad, I didn't read the code properly x)
