### ISSUE TITLE
[Discussion] Centralizing the issues in one repository

### ISSUE THREAD

**Issue by TheFrenchGhosty** [iv-org/invidious#2120]
This is a discussion mainly for the organization members (@Perflyst @B0pol @cloudrac3r @hackerncoder @saltycrys @SamantazFox @syeopite @unixfox) but others are free to give their opinion: 

Currently we have 14 repositories to manage, if we fork some of the unmaintained dependencies we use, this will bring this number higher.

This is a massive problem to handle issues, some issues in the less active repositories are sometimes opened for 1+ month before anyone see them.

In my opinion, we should: 

- centralize all issues here using the "type" labels to "affect" them to a repository (that isn't this one), for example `type:lsquic-cr`.
- transfer all the issues (open and, if possible, closed) to this repository
- disable the issues in every other repositories

This will ease *everyone* jobs, including the job of people reporting issues.

**Comment by SamantazFox** [comment]
I agree on that, except maybe for the documentation repo.

**Comment by TheFrenchGhosty** [comment]
@SamantazFox 

> I agree on that, except maybe for the documentation repo.

Half of the documentation related issues are already here with `type:documentation`: https://github.com/iv-org/invidious/issues?q=is%3Aissue+label%3Atype%3Adocumentation

**Comment by SamantazFox** [comment]
> Half of the documentation related issues are already here with `type:documentation`: https://github.com/iv-org/invidious/issues?q=is%3Aissue+label%3Atype%3Adocumentation

mmh, right.

**Comment by B0pol** [comment]
I disagree.

It already exists, it's the project feed
https://github.com/orgs/iv-org/dashboard

It centralizes all repos. You can easily follow every changes, new messages, new PR, new issues on all repo with the project feed.
You can also subscribe to the RSS feed if you want.

Most repos are libraries / other projects used by invidious but not invidious directly, therefore (imo) it makes sense to have a separate issue tracker otherwise all different projects will be flooded by invidious's issue.

---

> Half of the documentation related issues are already here with type:documentation

They should be moved to the doc repo

**Comment by cloudrac3r** [comment]
I don't think my thoughts are relevant here. Go for it I guess.

**Comment by syeopite** [comment]
I'm with @B0pol on this one.

**Comment by hackerncoder** [comment]
My experience with how Qubes has one specific repo for bugs has been fine. No objection from here.

**Comment by unixfox** [comment]
I'm against the centralization of the issues because I like when the issues are separated from each other because every repo under the iv-org is a separate component with its own usage. Take for instance lsquic.cr could be used by other projects than invidious because it's a general crystal library for doing QUIC requests.

If you want to get a better organization of the issues then start to use GitHub projects in order to classify the important issues under a same place called "Projects" and accessible from a tab: https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards

**Comment by TheFrenchGhosty** [comment]
Issues will be kept separated.
