### ISSUE TITLE
iOS application like newPipe

### ISSUE THREAD

**Issue by theopensour** [iv-org/invidious#2125]
**Is your enhancement request related to a problem? Please describe.**

No not really I was just wondering if there was a way to turn this into a mobile app for iOS not on AppStore but in Cydia there is app called invid which sort of does this but is not a full on mobile app and so is not as fast
**Describe the solution you'd like**

Creating mobile app That is like newpipe on Android 
**Describe alternatives you've considered**

**Additional context**

**Comment by Nassim-Saboundji** [comment]
Unfortunately I don't think it's possible to distribute an iOS that does what invidious does because Apple would simply remove it.
Here are more details : https://stackoverflow.com/questions/59904678/is-it-allowed-to-play-a-youtube-video-within-a-flutter-app
The first answer is relevant to the discussion.

**Comment by SamantazFox** [comment]
Sorry, but invidious is only a web front-end. As already mentionned in #306, there won't be any Android / iOS applications.
