### ISSUE TITLE
[Bug] Error to view video

### ISSUE THREAD

**Issue by HumanG33k** [iv-org/invidious#2136]
I do a migration reinstall from an old server (not same cpu architecture )

I import the database follow install instruction (for debian) rerun it because the doc was not up to date.
i can't start a video  

```bash
Title: `unknown result set attribute: title (DB::MappingException)`
Date: `2021-06-07T22:42:15Z`
Route: `/watch?v=q8lxYswKJU8`
Version: `2021.06.07-d827346 @ master`
<details>
<summary>Backtrace</summary>
<p>
   
'''
unknown result set attribute: title (DB::MappingException)
  from src/invidious/videos.cr:551:0 in 'on_unknown_db_column'
  from lib/db/src/db/serializable.cr:105:7 in 'query_one?:as'
  from src/invidious/videos.cr:940:7 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
'''
</p>
</details>
```

**Comment by SamantazFox** [comment]
Have you followed the ["updating" instructions](https://github.com/iv-org/documentation/blob/master/Updating.md)?

The likely reason is that you forgot to run one of the SQL migration scripts.

**Comment by HumanG33k** [comment]
yes i did

**Comment by SamantazFox** [comment]
> I think is missing some if exist in instruction ?

it's right here: `[ -f $file ] && $file` ^^

The script will listall commits from `old` to `new`, prepare the path to the file, and if such file exists, execute it. Here is the command line from the docs, but wrapped for clarity:
```bash
for i in `git rev-list --reverse --abbrev-commit $currentVersion..HEAD` ; do
    file=./config/migrate-scripts/migrate-db-$i.sh ;
    [ -f $file ] && $file ;            # <= If file exists, run it.
done
```

**Comment by HumanG33k** [comment]
So the test for sql data is a existing file test ?

**Comment by SamantazFox** [comment]
> So the test for sql data is a existing file test ?

Yes. Every time a change is made to the database structure, a SQL migration script is added in `config/migrate-scripts/`. Those SQL scripts are named after the commit hash where the change was introduced.

For instance, the script [migrate-db-1eca969.sh](https://github.com/iv-org/invidious/tree/master/config/migrate-scripts/migrate-db-1eca969.sh) was added because the commit https://github.com/iv-org/invidious/commit/1eca969cf6b4096789014619285c98d1def40ee3 changed the database structure.

The code simply checks if any of those scripts apply to your upgrade case, by listing all the commit hashes that weren't here before doing `git pull` and verifying that associated migration script(s) exist.

**Comment by HumanG33k** [comment]
So if we start with a fresh code but an old version of the database ? It works or not ? Because it's my use case. Not sure git clone works as a pull. If i understand well the good working of an sql update is based on 3 layer ? database, file system, git.

**Comment by SamantazFox** [comment]
> So if we start with a fresh code but an old version of the database ? It works or not ? Because it's my use case.

The SQL migration scripts are exactly that: they make changes to an old database to work with newer code!

>  Not sure git clone works as a pull. If i understand well the good working of an sql update is based on 3 layer ? database, file system, git.

No. The recommended way to update the database is to `git pull` the new code.

What was the previous version of your invidious instance, before the update?

> Also maybe related to build step because i firstly use the last crystal version V1 but invidious need the v0.36 (if remember). There is a clean option in building step with crystal ?

[Invidious has support for Crystal v1.0.0 since today!](https://github.com/iv-org/invidious/commit/a6e38e2ad2e0bce9ac5c08e1e6853a0c0c13e781) You can try again :)

**Comment by HumanG33k** [comment]
What was the previous version of your invidious instance, before the update? 

=> a do not remember, last was when my instance stop to work months ago. (crystal stop to maintain crystal version for my old cpu architecture) If i remember well before the creator stop. 

"Real" sql migration have a way to downgrade even if most dev do not care. (or not take time to). I do not know who write migrations but invidious should maybe use functionnal(transactionnal not sure about good english word for that)  upgrade (check guix)

No even the same message. 

```
Title: `unknown result set attribute: title (DB::MappingException)`
Date: `2021-06-11T22:38:51Z`
Route: `/watch?v=rAxbuhEJEzs`
Version: `2021.06.11-fe64e6d @ master`
<details>
<summary>Backtrace</summary>
<p>
   

unknown result set attribute: title (DB::MappingException)
  from src/invidious/videos.cr:551:0 in 'on_unknown_db_column'
  from lib/db/src/db/serializable.cr:105:7 in 'query_one?:as'
  from src/invidious/videos.cr:940:7 in 'get_video:region'
  from src/invidious/routes/watch.cr:61:15 in 'handle'
  from lib/kemal/src/kemal/route.cr:13:9 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/static_file_handler.cr:189:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/init_handler.cr:12:7 in 'process'
  from /usr/share/crystal/src/http/server.cr:498:5 in '->'
  from /usr/share/crystal/src/primitives.cr:255:3 in 'run'
  from ???
'''
</p>

```

**Comment by SamantazFox** [comment]
> "Real" sql migration have a way to downgrade even if most dev do not care. (or not take time to). I do not know who write migrations but invidious should maybe use functionnal(transactionnal not sure about good english word for that) upgrade (check guix)

We don't make downgrade available fo rthe simple reason that, as youtube-dl, we're dependent on whanges youtube make. So going to an older version of the software is simply not going to work, not because we didn't made it possible, but because Google changes their stuff all the time.

Given the error messages, I'd recommend you to learn a bit of PostgreSQL, make a backup of your database, run your instance on a fresh database, and then try to migrate manually the data from your backup.
