### ISSUE TITLE
Is there a public instance of invididous which does not require sharing your google identity ?

### ISSUE THREAD

**Issue by shirishag75** [iv-org/invidious#2143]
I looked at this page https://docs.invidious.io/Invidious-Instances.md but it seems almost all the public ones need you to share your google identity. Couldn't there be a third-party service where you register and have a unique username password which would be different from your google id and you could still add videos which you liked and wanted to backup on a different site, so if the video does get censored or is privatised whatever, it is still fully there on the site. And of course, you can share the content with other people. If this has been asked before, please share the link of the issue/conversation here. Thank you.

**Comment by unixfox** [comment]
Hum the point of Invidious is that you don't need any Google identity, you may register an account that is only accessible from the Invidious software and tied to no Google identity. With this account you get almost all the same functionalities as with a Google account except the ability to like videos because you can't like a video without a Google account.

Also, Invidious doesn't store any video feed because it only acts like a proxy to YouTube servers. Backuping videos is a non goal for Invidious, Omar already talked about this here: https://github.com/iv-org/invidious/issues/899#issuecomment-553623686

I think you misunderstood part of the features of this project.
