### ISSUE TITLE
"Connection is not private" message[Bug] 

### ISSUE THREAD

**Issue by nathgit** [iv-org/invidious#2197]
**Describe the bug**
When I visit the invidious.snopyta.org instance it shows the message "Connection is not private".

**Steps to Reproduce**
1. Go to 'invidious.snopyta.org'
2.  See error

**Additional context**

 - Browser (if applicable):
 - Chrome OS

**Comment by unixfox** [comment]
Please stop reporting issues that only occur on snopyta, this is a place to report the issues that you can replicate on multiple invidious instances or when running invidious locally.

If you are having some issue with the instance then:
- contact perflyst
- switch to another working instance: https://redirect.invidious.io

**Comment by nathgit** [comment]
The thing is I have tried several different instances. They all have problems. I only use snopyta because in general it seems to be the most stable.

**Comment by unixfox** [comment]
On GitHub, the Invidious team only manage the code of Invidious and not the instances publicly listed on redirect.invidious.io. Reporting the bugs that you can't replicate on other instances won't help because we have no control over the public instances.

If you want a great Invidious experience you can run your own Invidious instance locally, we have a great documentation that explain how to do it: https://docs.invidious.io/Installation.md. Try Docker and you will get a working Invidious under half an hour.

**Comment by SamantazFox** [comment]
> The thing is I have tried several different instances. They all have problems. I only use snopyta because in general it seems to be the most stable.

We're reviewing the instances list on a regular basis, to make sure that none gets outdated (and hence broken). There are new instances that have been added recently: https://github.com/iv-org/documentation/blob/master/Invidious-Instances.md
