### ISSUE TITLE
[Bug] No video with supported format and MIME type found

### ISSUE THREAD

**Issue by BumiMandias** [iv-org/invidious#2212]
All WEBM files on tor provide this, No video with supported format and MIME type found. Happens on this website aswell, if you know a fix or could fix this. Please let me know.

**Comment by SamantazFox** [comment]
Could you please provide more informations, like exact error message and the exact steps to reproduce your problem?

**Comment by BumiMandias** [comment]
TOR > Website that shows webm video files > Play > Says No video with supported format and MIME type found

**Comment by SamantazFox** [comment]
@BumiMandias have you tried to go to invidious settings and check "proxy videos"?
![image](https://user-images.githubusercontent.com/52980486/123560811-ea460d80-d7a4-11eb-9997-4b3a41893bbf.png)

**Comment by unixfox** [comment]
Closing in favor of https://github.com/iv-org/invidious/issues/602 and https://github.com/iv-org/invidious/issues/2850

This issue is likely going to be somewhat fixed in https://github.com/iv-org/invidious/pull/3011

Please also read about this issue in the documentation: https://github.com/iv-org/documentation/blob/master/docs/faq.md#q-the-media-could-not-be-loaded
