### ISSUE TITLE
Play all videos from channel

### ISSUE THREAD

**Issue by Discookie** [iv-org/invidious#234]
There should be an option to "Play All" from a channel, even from those that don't have an `Uploads` playlist.

I'm thinking of something like `&feature=mfu_in_order&list=UL` was before Youtube changed it.  
It played the "More from user" playlist, which had all uploads from a channel.

**Comment by Discookie** [comment]
Apparently the playlist `UU<channelid>` contains all uploads from a channel, such as:

https://invidio.us/playlist?list=UU5nc_ZtjKW1htCVZVRxlQAQ 
(for channel [UC5nc_ZtjKW1htCVZVRxlQAQ](https://invidio.us/channel/UC5nc_ZtjKW1htCVZVRxlQAQ))

Also works if the playlist is `UC<channelid>`.

Along the same lines, `PU<channelid>` contains the "Popular uploads" playlist, even though Invidious fails to load it for some reason.

https://www.youtube.com/watch?v=ih2xubMaZWI&list=PU5nc_ZtjKW1htCVZVRxlQAQ

**Comment by omarroth** [comment]
The reason this hasn't been closed in favor of `UU<channelid>` is because it's *not* guaranteed to get all videos from a channel, see [this thread](https://www.reddit.com/r/DataHoarder/comments/9ir3v8/youtube_uploads_playlist_not_showing_all_uploads/) for an example. I have not found a good way to find videos that would be missing. 

The current roadmap for this feature is to implement a custom `UL<channelid>` playlist, which uses the same functionality as the `<channelid>/videos` page, which appears to get mostly everything.

YouTube fails to load the `PU<channelid>` as well if you try to load it like this:

https://www.youtube.com/playlist?list=PU5nc_ZtjKW1htCVZVRxlQAQ&pbjreload=10&disable_polymer=1

So I'm assuming it's a something like a  "psuedo-playlist", similar to mixes.
