### ISSUE TITLE
[Feature request]  Download to server for admin

### ISSUE THREAD

**Issue by kklot** [iv-org/invidious#2387]
**Describe the solution you'd like**
selfhosted Invidious with an option to "Save to server" where the admin can specify a default path.

**Additional context**
Save to Jellyfin managed locations

**Comment by unixfox** [comment]
What do you mean by save to server? Like downloading a video directly to a path on the server?

**Comment by kklot** [comment]
Yes, does that make sense?

**Comment by unixfox** [comment]
> Yes, does that make sense?

I don't think we are going to implement something like this because there are already a lot of existing tools for that.

An example is youtube-dl: https://youtube-dl.org/

If you don't like command line then you can use web ui for youtube-dl like this project: https://github.com/d0u9/youtube-dl-webui

**Comment by TheFrenchGhosty** [comment]
It's completely out of scope.

Invidious isn't a downloader it never was, and never will be. Stick youtube-dl/yt-dlp and projects using it.

**Comment by kklot** [comment]
Well OK then. I would not have asked if there is not a prominent `Download` button with a lot of options to chose from. 
Thanks.

**Comment by TheFrenchGhosty** [comment]
@kklot I agree that this is indeed a problem.

See: https://github.com/iv-org/invidious/issues/1563 we plan to heavily change it.
