### ISSUE TITLE
[Bug] Subtitles are sometimes positioned outside of the video

### ISSUE THREAD

**Issue by Cat-Ion** [iv-org/invidious#2391]
**Describe the bug**
In at least one video, some of the subtitles are not placed within the video area.

**Steps to Reproduce**
1. Go to https://vro.omcat.info/watch?v=Q7OrGfblPlM
2. Enable subtitles
3. Wait for first subtitle at ~5 seconds
4. The subtitle is centered above the bottom right corner of the video

**Screenshots**
![image](https://user-images.githubusercontent.com/443968/132841738-47a3c882-867e-48a9-87d1-8ee52a3c86e3.png)

**Additional context**
 - Browser (if applicable): Firefox 90
 - OS (if applicable): Linux
 - Apparently the subs were created with https://github.com/arcusmaximus/YTSubConverter
 - https://invidious.snopyta.org/watch?v=Q7OrGfblPlM  seems to not show the subs at all, while https://inv.riverside.rocks/watch?v=Q7OrGfblPlM has them

**Comment by SamantazFox** [comment]
thanks for reporting that! Looks like a bug with VideoJS, so as many other issues, this has probably already been fixed by upstream. We have to update to the latest version on our side this is in our to-do list. Sorry for the inconvenience.

In the meantime, if you already use an extension like Stylus, you can use the following CSS snippet:
```css
.vjs-text-track-cue, .vjs-text-track-cue-0 {
	inset: 658.983px 0px 0px 0px !important;
}
```

**Comment by Cat-Ion** [comment]
Thanks, that worked!

**Comment by TheFrenchGhosty** [comment]
A 5$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 5$ (in BTC) from the Invidious project.

More details: #1898
