### ISSUE TITLE
[Feature Request] Allow disabling of the standard player

### ISSUE THREAD

**Issue by Wittmaxi** [iv-org/invidious#240]
Though it looking kinda cool, I don't like the standard player because it still has too many bugs (stopping media flow entirely even though the network is still going etc [I can't really find a pattern on how to reproduce those bugs, but if I do, i'll report em]) to be really used.

**Comment by omarroth** [comment]
Most problems with playback will probably be fixed with #34, since DASH is able to accommodate issues in network, sources changing, etc. I expect the problem you encounter with stopping media is due to the source expiring, for example [this](https://r4---sn-vgqskne6.googlevideo.com/videoplayback?ip=2604%3Aa880%3A400%3Ad1%3A%3A6b6%3Ab001&key=cms1&signature=3102B92DAD05070BF3D387698BFBE9F20D4881EF.4BBA35FE73ACD46C23C8DAC1D78451E121DB6729&id=o-AJdFUasp7UtBaKYt8Xds9G4UUTHEXATy5SEM54FGOD3k&ei=xnHwW7_tOJrehgbLmbrQAQ&dur=0.000&lmt=1536989764617997&source=youtube&fvip=4&c=WEB&pl=22&itag=43&requiressl=yes&clen=55995429&mime=video%2Fwebm&ipbits=0&ratebypass=yes&expire=1542506023&sparams=clen,dur,ei,expire,gir,id,ip,ipbits,ipbypass,itag,lmt,mime,mip,mm,mn,ms,mv,pl,ratebypass,requiressl,source&gir=yes&redirect_counter=1&rm=sn-ab5rk76&fexp=23763603&req_id=7806ba566ce6a3ee&cms_redirect=yes&ipbypass=yes&mip=166.175.60.241&mm=31&mn=sn-vgqskne6&ms=au&mt=1542484322&mv=m) link has an `&expire=1542506023` which is roughly 6 hours in the future (at the time this was written).
