### ISSUE TITLE
[Bug] Closing a reddit comment thread redirects to homepage

### ISSUE THREAD

**Issue by namazso** [iv-org/invidious#2412]
**Describe the bug**
if you click the `[-]` button next to a reddit comment thread it will redirect you to homepage instead of closing.

**Steps to Reproduce**
1. click on `[-]` on any reddit comment thread
2. you're redirected to /void(0)

**Screenshots**
![image](https://user-images.githubusercontent.com/8676443/133924412-910667a7-a698-4c64-8a67-374092b27be3.png)

**Comment by TheFrenchGhosty** [comment]
`void(0)` is used to trigger some JS.

For example to open the Reddit comments: you click on "View Reddit comments" that link to "javascript:void(0)"

I'm guessing it's a mistake someone made in the code and instead of "javascript:" it's the instance URL.

**Comment by TheFrenchGhosty** [comment]
A 10$ bounty has been added to this issue.

Anyone opening a PR fixing this issue, will receive 10$ (in BTC) from the Invidious project.

More details: #1898

**Comment by fristys** [comment]
Can confirm this is still an issue. Any progress on it?

Also, instead of relying on `javascript:void()`, wouldn't be more sensible to actually use `event.preventDefault()` somewhere here https://github.com/iv-org/invidious/blob/e2fc64296dacf6ce8a406183c1bb6388dce6d117/assets/js/handlers.js#L16 ? Or maybe add an extra `data-` attribute to specify whether the event should be prevented or bubbling should be stopped and then use that in the handlers file?

**Comment by TheFrenchGhosty** [comment]
@fristys 

>Any progress on it?

I don't think so.

>Also, instead of relying on javascript:void(), wouldn't be more sensible to actually use event.preventDefault() somewhere here 

Maybe? The JS hasn't really ever been changed since no one in the team is a JavaScript developer.

**Comment by fristys** [comment]
> > Also, instead of relying on javascript:void(), wouldn't be more sensible to actually use event.preventDefault() somewhere here
> 
> Maybe? The JS hasn't really ever been changed since no one in the team is a JavaScript developer.

Normally, I'd offer my help, but, sadly, at this time my day job doesn't give me a lot of spare time.

 I think it's a good practice to use `preventDefault` / `stopImmediatePropagation` instead of voids (it'll also save you having to write the whole url thing). It gives you more control over event handling, and a guarantee that native browser events don't get triggered when you don't want them to.

**Comment by SamantazFox** [comment]
@fristys yes, in the future I'd like to rewrite all links with `data-*` attributes and register event handlers in JS.
And as ghosty said, there aren't JS devs in the team, so PRs are much welcome :)
