### ISSUE TITLE
Service start failed. Permission denied

### ISSUE THREAD

**Issue by Happyfeet01** [iv-org/invidious#2426]
**Debian 10**
**latest Invidious Version**
**Apache2 Apache/2.4.38 (Debian)**

Hello,

i try to start Individious. But the Service cant be start.

Sep 24 10:45:30 dns systemd[1]: Started Invidious (An alternative YouTube front-end).
Sep 24 10:45:30 dns systemd[23687]: invidious.service: Failed to execute command: Permission denied
Sep 24 10:45:30 dns systemd[23687]: invidious.service: Failed at step EXEC spawning /home/domain/domains/yt.domain.tld/public_html/invidious: Permission denied
Sep 24 10:45:30 dns systemd[1]: invidious.service: Main process exited, code=exited, status=203/EXEC
Sep 24 10:45:30 dns systemd[1]: invidious.service: Failed with result 'exit-code'.``

The Service File:

```
[Unit]
Description=Invidious (An alternative YouTube front-end)
After=syslog.target
After=network.target

[Service]
RestartSec=2s
Type=simple

User=domain
Group=domain

WorkingDirectory=/home/domain/domains/yt.domain.tld/public_html/invidious
ExecStart=/home/domain/domains/yt.domain.tld/public_html/invidious -o invidious.log

Restart=always

[Install]
WantedBy=multi-user.target``
```

The Apache2 User "domain" is correct, because i use [Virtualmin](https://virtualmin.com) as GUI for manage my Servers.

Every User on this Server has different Apache2 User. 

But why i got an permissions denied Error?

**Comment by unixfox** [comment]
Please post the output of:
```
ls -l /home/domain/domains/yt.domain.tld/public_html/invidious
```

**Comment by Happyfeet01** [comment]
@unixfox 
![Screenshot_20210924_201717](https://user-images.githubusercontent.com/3295104/134722213-bd938dcf-9090-44e8-b78a-1b5feeca768d.jpg)

**Comment by unixfox** [comment]
As you can see it's most likely a permission issue. Your user larsmueller doesn't have access to the invidious file.

You should look into changing the owner of the file with the chown command.

I'm going to close this issue because this github issues is not a tech support forum about general Linux issues. This is dedicated to issues directly related to issues with invidious.

If you want to get more help then join our matrix room (invidious on matrix.org) and some people will be able to spend their free time helping you but here we don't have the free time to help you with basic usage of Linux.

**Comment by Happyfeet01** [comment]
Sure larsmueller has no access. But the correct User for apache. Here with *sudo -u* has the correct permission.   This is, why i ask...
