### ISSUE TITLE
[Feature request] Setting to use Youtube embeded video player

### ISSUE THREAD

**Issue by trymeouteh** [iv-org/invidious#2458]
Please add an setting to use the Youtube embedded video player to watch videos on Invidious and not have Invidious grab and process the videos for the users privacy.

I use Brave for a browser and other privacy technologies and I am not afraid of using Youtube.com or connecting to it. However I like Invidious for its degoogled subscription feed to Youtube channels. Such a setting can help reduce the load on a Invidious server for not needing to process the video for the users privacy.

**Comment by unixfox** [comment]
Mmmh I am not sure if it's even a good idea, this goes against any reason why Invidious was created in the first place.

By using the official YouTube player, you will get tracked by YouTube all the time, even if you don't have a Google account.

If you want to have a degoogled subscription feed, I think you are better off using an RSS client and subscribe to the RSS feeds of all the channels that you like. This way you are notified for any new videos, and you can watch the videos using the official YouTube player.

**Comment by syeopite** [comment]
Unfortunately, although this has been requested before, we are not accepting this due to the gross privacy issues. See https://github.com/iv-org/invidious/issues/237#issuecomment-911687710 for more details. If there are significant requests for this feature, we might reconsider though but for now, it's a definite no from us.
