### ISSUE TITLE
[Bug] undefined volumes in postgres

### ISSUE THREAD

**Issue by schklom** [iv-org/invidious#2561]
**Describe the bug**
The volumes in the postgres service need to be copied from the repo manually.

**Steps to Reproduce**
1. Copy the docker-compose.yml from https://docs.invidious.io/Installation.md#create-docker-compose-file
2. run `docker-compose up -d`
3. Fail because
```yaml
- ./config/sql:/config/sql
- ./docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh
```
`./config/sql` and ` ./docker/init-invidious-db.sh` are created automatically as directories

If I simply copy and paste the files from github to these volumes on my machine, then the files on my machine will never update whenever someone updates them on GitHub.
These files will be updated on GitHub at some point, and I don't want to have to debug for hours to realize that they were never updated on my machine.

**Request**
Execute the script from Invidious directly if the tables are not present.

**Comment by SamantazFox** [comment]
yeah, there is an issue in the docs, you're supposed to clone the repository, then replace the content of `docker-compose.yml` with the content from the docs and _then_ run `docker-compose up`

**Comment by schklom** [comment]
It looks like it is to execute a script the 1st time that the database is created.
Why not simply run the following everytime from the invidious container?
1. check database is running
2. if tables (`public.annotations` etc from `config/sql/*`) don't exist, create them

Is there a reason to not do this? It would avoid this entire situation of setting up a volume manually.

It would take me a while because it has been a while since I worked with SQL, but I could try to code it for the Dockerfile on my spare time.

**Comment by SamantazFox** [comment]
> It looks like it is to execute a script the 1st time that the database is created. Why not simply run the following everytime from the invidious container?
> 1. check database is running
> 2. if tables (`public.annotations` etc from `config/sql/*`) don't exist, create them

The `config/sql/*.sql` files should be present in the container, so you can use the [`check_tables` config option](https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L35) and invidious will create the tables:
https://github.com/iv-org/invidious/blob/afb284fa9baa4c199f6770651f5a5d4ef01f2d9f/src/invidious/helpers/helpers.cr#L75-L85

Though, this is quite a hacky way of doing it and it's not really recommended (if you use that option, make sure to disable it afterwards).

> Is there a reason to not do this? It would let users avoid having to copy a repo just for this.

Yes. It's because we don't have an adapted database migration system yet. We need to have that before making any changes to the database system.

This is something we have planned, and some PRs have been blocked for quite some time because of that, but it requires time and we're only a small team of volunteers. So please be patient :)

**Comment by unixfox** [comment]
@SamantazFox this is fixed right?

**Comment by SamantazFox** [comment]
@unixfox not yet. We've merged Matthew's code for auto-migrations, but it's not active by default yet. We need to test it.

**Comment by schklom** [comment]
The documentation has been updated, but I think the problem remains, no?

Will `init-invidious-db.sh` be automatically updated in the container after the repository's version updates?
