### ISSUE TITLE
[Bug] No captions

### ISSUE THREAD

**Issue by DUOLabs333** [iv-org/invidious#2565]
**Describe the bug**
If you try to turn on captions for a video on an instance, nothing pops up

**Steps to Reproduce**
1. Go to any video with a caption
2. Click on a caption

**Comment by unixfox** [comment]
Which instance did you test?

**Comment by DUOLabs333** [comment]
Kavinrocks and snopyta

**Comment by unixfox** [comment]
Captions are blocked on popular invidious instances, as google is blocking the servers that are requesting too many captions at the same time.

If you want the captions to work then use a less popular invidious public instance or host invidious yourself.

I'm going to close this issue in favor of this one: https://github.com/iv-org/invidious/issues/2567 because it describes how to fix the original issue that you are having on big public instances.
