### ISSUE TITLE
[Discussion] Database migrations framework

### ISSUE THREAD

**Issue by SamantazFox** [iv-org/invidious#2620]
This subject is a bit related to #2498, as most database migration tools come with a web framework.

We **must** use a database migration engine before doing any changes to the DB (like #2469), in order to avoid issues that could be caused by a manual migration. It will also ease the initial DB deployment by not requiring the script file currently used for docker, that prevents the dockerfile/docker-compose files to be used standalone, without cloning.

This issue is a discussion around the different options available, their pros and their cons.

Personally, my vote will be either for micrate or a fork of mg to implement MySQL/PGSQL support.

## Candidtates

- [amberframework/micrate](https://github.com/amberframework/micrate)
  * **Pros**
    - Supports all major DB types: PGSQL, MySQL and SQLite
    - Is independant from the amber framework (no dependencies other than the DB drivers)
  * **Cons**
    - DB migrations folder path is hard-coded, so only one of the DB types can be used at once
    - DB migrations can only be in separate SQL files. They can't be embedded in the final crystal executable.
    - Unknown license (see https://github.com/amberframework/micrate/issues/81)

- [luckyframework/avram](https://github.com/luckyframework/avram)
  * **Pros**
    - Has its own "abstraction language". No need to write heavy SQL statements ourselves.
    - Integrates with the rest of the lucky framework
    - Active development
  * **Cons**
    - Heavily depends on the lucy framework (implies that we'll use it for the web part, too)
    - Only supports PGSQL (and this will probably never change)
    - Very complex, because of that "abstraction language"

- [hkalexling/mg](https://github.com/hkalexling/mg)
  * **Pros**
    - Extremely simple
    - SQL statements are embedded in Crystal classes with `up` and `down` methods
  * **Cons**
    - Only supports SQLite

- [vladfaust/migrate.cr](https://github.com/vladfaust/migrate.cr)
  * **Pros**
    - Migration folder can be specified at initialization (unlike micrate) 
  * **Cons**
    - Outdated (last commit from August 2019, shard.yml refers to an old version of crystal)
    - DB migrations can only be in separate SQL files. They can't be embedded in the final crystal executable.
    - Only supports PGSQL

**Comment by TheFrenchGhosty** [comment]
Discussed in Matrix (this is a summary/copy-paste of what I sent): I'm for going with Avram, by far.

---

Amber is basically dead https://github.com/amberframework/amber/commits/master

3/4 of the org members are inactive/not working on it actively:

https://github.com/c910335 nothing since october
https://github.com/damianham nothing since 2020
https://github.com/drujensen low activity but active
https://github.com/elorest almost nothing ever
https://github.com/faustinoaq almost nothing ever
https://github.com/fridgerator low activity but active
https://github.com/jwaldrip low activity but active
https://github.com/maiha almost nothing ever
https://github.com/marksiemers nothing since june 2020
https://github.com/robacarp active
https://github.com/Sija active
https://github.com/veelenga active

---


Lucky is the most active framework https://github.com/luckyframework/lucky/commits/master

With an active team:

https://github.com/edwardloveall active
https://github.com/jwoertink active
https://github.com/matthewmcgarvey active
https://github.com/paulcsmith active
https://github.com/stephendolan active

---

mg is using sqlite, so it obviously doesn't work

---

migrate.cr requires us to do even more work, something we can't afford.

---

### TL;DR:

Going with something other than Avram is a REALLY bad idea, unless we want to fork/contribute to the project every time we need something.

**Comment by TheFrenchGhosty** [comment]
@matthewmcgarvey Since you work on Lucky, I'm interested in your opinion.

**Comment by matthewmcgarvey** [comment]
Like the post says, Avram will only ever support postgres. I've not looked too much into Invisious' db config, but I thought invidious supported sqlite? That would cross avram off the list immediately.

If that's not an issue, I think it would work fine but there are some anti patterns to watch out for.

This might be another to look into https://github.com/jgaskins/interro. I doubt it's used much but the creator is really active.

If these wont work, I doubt that micrates would be too much work to fork and get it working for our needs

**Comment by SamantazFox** [comment]
> Like the post says, Avram will only ever support postgres. I've not looked too much into Invisious' db config, but I thought invidious supported sqlite? That would cross avram off the list immediately.

The only place where SQLite is used is in the user import, because of NewPipe files import:
https://github.com/iv-org/invidious/blob/823121637146c4b5b13ab4f4326cb73ff16828d6/src/invidious.cr#L871-L877

Though, there is #1675, which is imho a key feature to implement, and would require SQLite to provide the base functionality (mostly user features like watch history, playlists, and subscriptions).

> This might be another to look into https://github.com/jgaskins/interro. I doubt it's used much but the creator is really active.

Oh nice, will look into it. Though, at a first glance it doesn't allow to easily have 2 or more DB types next to eachother.

**Comment by matthewmcgarvey** [comment]
Ok, hear me out here... but what if we just made our own migration tooling? It's really not that complicated... and I'm not trying to brag or anything just look at https://github.com/amberframework/micrate

My understanding of our needs/wants:

- Needs to be embeddable in the source code
- Needs to be run when the app starts
- Migrations are added to, not edited
- Keep up with ran migrations and only run new ones
- Should be run in transaction so that failed migrations don't leave the app in a bad state
- Should fail loudly on failure (loudly as in a good error and the app doesn't try to continue running)
- Not database specific in implementation (should work on postgres, mysql, sqlite) (the migration code, not necessarily the specific migrations)

Things that other migration tools have that I don't think is a MUST have for us and some might not be wanted at all:
- CLI tooling
- DSL, we'd just use raw sql in strings
- Rollback, because invidious is run by many people, failing forward will probably always be better than asking people to undo migrations
