### ISSUE TITLE
[Feature request] (QUICK / Urgent!!) Help archiving dislikes

### ISSUE THREAD

**Issue by Myzel394** [iv-org/invidious#2707]
**Is your feature request related to a problem? Please describe.**

Youtube is going to remove the public dislike counter. https://returnyoutubedislike.com is a project which aims to bring it back and archive it. [When you have the extension installed and watch a video which hasn't been archived yet, it will be stored](https://returnyoutubedislike.com/faq).

**Describe the solution you'd like**
Send all video ids which are opened in Invidious to their API to help archiving dislikes.

**Describe alternatives you've considered**
[archiveteam.org](http://tracker.archiveteam.org/youtube-dislikes/) also offers archiving, which could also be used.

**Additional context**
This feature needs to be addressed quickly as we don't have much time left (Youtube is going to remove the dislike button counter ultimately on December 13.) and server owners also need to update their instances once this feature is added.

**Comment by Myzel394** [comment]
Did some light digging and it seems like [this api call is sending the votes](https://github.com/Anarios/return-youtube-dislike/blob/main/Extensions/chrome/return-youtube-dislike.background.js#L43)

**Comment by unixfox** [comment]
> Send all video ids which are opened in Invidious to their API to help archiving dislikes.

While I really like the initiative, I don't think we are going to do that due to obvious privacy reasons. Every video that an Invidious instance would watch would be automatically sent to a remote server, that's not a good idea because the remote server could literally build a profile of the invidious instance based on the IP address.

**Comment by TheFrenchGhosty** [comment]
I definitely agree with @unixfox here.

Also, just an FYI:  the whole backend of "returnyoutubedislike.com" is closed source, and the creators instantly close issues that ask for it, I wouldn't trust them.

The project itself is completely pointless... since it's basically currently just using the API, and when the access gets cut off (on december 13), the website will basically have the dislike of some thousands videos (at best).

I'm strongly in favor of just having people run archiveteam warrior though.

**Comment by Myzel394** [comment]
Okay that makes sense - Maybe we could add some awareness to the README.md ?

**Comment by unixfox** [comment]
Closing this issue as we don't want to implement this feature, sorry. But you can still discuss here.

**Comment by Myzel394** [comment]
> that's not a good idea because the remote server could literally build a profile of the invidious instance based on the IP address.

However, I don't fully understand this. Afaik invidious instances aren't meant to be private (since there is literally an API which lists all available instances (which fulfill the requirements)) :O

**Comment by unixfox** [comment]
> > that's not a good idea because the remote server could literally build a profile of the invidious instance based on the IP address.
> 
> However, I don't fully understand this. Afaik invidious instances aren't meant to be private (since there is literally an API which lists all available instances (which fulfill the requirements)) :O

The API only list the public instances, there are thousands of private invidious instances that we don't know the existence.

**Comment by Myzel394** [comment]
> The API only list the public instances, there are thousands of private invidious instances that we don't know the existence.

Okay never heard of any other instance besides the public ones, but I can imagine that there are private ones too.

We could still send videos to the archiveteam tough. They seem a bit more trustworthy and (to ensure private instances don't get leaked), the server could first do a check whether it's public or not (using the https://api.invidious.io/ api; and we'd also check whether it's type is "https" (and not onion for example))

**Comment by poltrian** [comment]
For me, dislikes are the precursor to hate. You can write in the comments that something is wrong or you disagree. I have never used dislikes before. And I've been on the internet for a very long time

**Comment by notracking** [comment]
I was looking for this same feature, because iPhone..

Managed to came up with a hacky solution to get sponsorblock integrated into my Invidious instance, by (ab)using the `banner:` option to inject a custom script directly into the html. Please note that for this to work `hsts:` must be disabled as the browser will otherwise block requests to the sponsorblock api.

First download `https://greasyfork.org/scripts/453551-sponsor-block-integration-invidious/code/Sponsor%20Block%20Integration%20%7C%20Invidious.user.js` to your Invidious `/assets/` folder and give it a sensible name like `sponsorblock_invidious.js` (edit this script to change the Sponsorblock settings).

Then update the `config/config.yml` and add the following lines
```
banner: <script type="text/javascript" src="/sponsorblock_invidious.js"></script>
hsts: false
```
Restart Invidious and you should be good to go!

I hope this will help someone in the future..
