### ISSUE TITLE
[Bug] <head> is loaded from other videos

### ISSUE THREAD

**Issue by andrigamerita** [iv-org/invidious#2913]
**Describe the bug**
Sometimes (I would say 1 in 50 chance), on any Invidious instance, opening a video page causes the \<body\> to load properly, but the \<head\> to be loaded from other videos.

**Steps to Reproduce**
- Go on any Invidious instance
- Open any video page
- If you're lucky, you will see the title in the browser tab not correspond to the video you opened, and the whole \<head\> html tag not corresponding in the page source, but actually being the valid \<head\> from another random video, probably one being opened at the same time by another user on the same instance

**Logs**
No logs seem to be generated in the browser, the issue is surely server-side, probably caching-related?

**Screenshots**
[Imgur](https://imgur.com/ISyjw9o)

**Additional context**
- Browser: Only tested with Chromium on Linux and Kiwi Browser on Android, but the issue seems to be server-side
- Incidents:
  - Last time this happened and I was able to record the issue properly was on 2022/02/17, on the instance invidious.kavin.rocks, running 2022.02.15-b24a89f@master
  - It happened at least 4 other times in the past on different instances, but I wasn't able to record

**Comment by unixfox** [comment]
I think it's only related to invidious.kavin.rocks because it uses cloudflare which may cache the HTML pages. We can't do anything as we have no control over the public instances.
For instance, I never encountered this issue on yewtu.be.
Closing as it's probably due to some cache introduced by a program between you and invidious, something that we have no control over.

**Comment by unixfox** [comment]
pinging @FireMasterK if he knows a bit about this issue.
