### ISSUE TITLE
[Bug] comments setting Generates more <option> elements if you add more elements to the list

### ISSUE THREAD

**Issue by ManeraKai** [iv-org/invidious#2964]
If you add more than 2 elements in the `comments` array in the cookies, it will generate more `<option>` elements:
![image](https://user-images.githubusercontent.com/40805353/158031301-a28229b9-ecf4-45b4-a99c-fccf97c7b94b.png)

Same if you add just 1 element in the `comments` array. It will show only 1 `<option>` element:
![image](https://user-images.githubusercontent.com/40805353/158031343-47adc0f1-ad1f-49f9-967b-4d822d550306.png)

**Comment by SamantazFox** [comment]
yeah, that's kinda-not-a-bug. The number of options is supposed to vary (5 if user is logged in, 3 otherwise). The number of fields to show is taken from the size of the array. As the user is not supposed to modifiy the cookie, that works for most people ^^

But I've been working (for quite some time now) on a rewrite of the preferences to improve input validation and the user interface in general (and also clean a **lot** the code).
