### ISSUE TITLE
[Bug] Cannot search within a specific channel

### ISSUE THREAD

**Issue by NintendoManiac64** [iv-org/invidious#3029]
This started happening a couple of weeks ago.  The following exact URL used to work:
- https://yewtu.be/search?q=channel%3AUCRPdsCVuH53rcbTcEkuY4uQ+rdna3

...but now it does not.  Similarly manually putting in a search query of the following gives the same error'd result:
- channel:UCRPdsCVuH53rcbTcEkuY4uQ rdna3

It's supposed to do a search for "rdna3" on the following channel:
- https://yewtu.be/channel/UCRPdsCVuH53rcbTcEkuY4uQ

**Comment by lassekongo83** [comment]
I noticed all search operators are broken. For example `search string duration:long` returns `Could not extract JSON. Youtube API returned error 400 with message: "Request contains an invalid argument."`. Removing the space from the search just returns: `No results found.`

**Comment by SamantazFox** [comment]
@NintendoManiac64 Ah, crap. I'll have to investigate. That'sone of the rare parts of the code that have a ton of test, and they all pass.

@lassekongo83 for all filters except `channel:`, it's preferred to use the UI (which sets URL parameters) rather than the legacy (query) filters. Though yeah, that's not supposed to break...
