### ISSUE TITLE
[Bug] SSL: TLSV1_ALERT_PROTOCOL_VERSION

### ISSUE THREAD

**Issue by antonic901** [iv-org/invidious#3147]
Hello to all. I'm in the process of making YouTube plugin for XBMC4Xbox which is version of Kodi for Original Xbox. I'm coding in Python 2.7.11 and I have problem with TLS protocol. I have no ways/knowledge to update Python or OpenSSL on Xbox. So my question is there any workaround for this? I had same problem with new OpenSubtitles API but developers were kind enough to disable this requiremenet.

Problem:
When I send HTTP request with requests I get error:
`
20:19:28 M: 91807744  NOTICE: urllib2
20:19:28 M: 91041792  NOTICE: .
20:19:28 M: 90972160  NOTICE: URLError
20:19:28 M: 90976256  NOTICE: :
20:19:28 M: 90857472  NOTICE: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:592)>
`
I know it's not a "bug", but maybe there is some fix for this. Also, I have one more question. Is this TLS/OpenSSL limitation coming from invidious project or it's restriction made by guys who are hosting API instances? For example, can I make Invidious API instance which will allow connection from old-based systems like Xbox?

**Comment by unixfox** [comment]
You can host your own invidious instance with TLS 1.0 enabled or "might" be better plain old unencrypted HTTP. We have a documentation about that here: https://docs.invidious.io/installation/

For the public instances, it's the owner of the instance that disabled the usage of TLS 1.0 & 1.1 not invidious. And we don't recommend enabling TLS 1.0 or TLS 1.1 because these are insecure TLS protocols.
