### ISSUE TITLE
[Enhancement] Support trimmed downloads

### ISSUE THREAD

**Issue by d00m514y3r** [iv-org/invidious#3212]
We can specify a part of a video to be played by `start` and `end` url arguments. It would be great to be able to download videos the same way, e.g. Downloading a single clip from a compilation video.

I tried providing `start` and `end` to the download links manually but it didn't work. I also tried pressing the download link in a video which has those argument in it's link but it downloaded the entire video instead

Thanks for all the hard work

**Comment by SamantazFox** [comment]
Hello! Sorry to say that, but that can't possibly be implemented.

1. This is not feasible on the server side because of the hardware requirements (instance owners would need to run extremely powerful and expensive servers with GPUs)

2. This is not feasible on the client side because there is currently no standardized JS API that permits video encoding (there is an experimental API on chrome only). Without a JS API, encoding would have to be done from scratch, and extremely slow (done on the CPU). And if there were a JS API, we would wait for a proper JS library, as the team doesn't have the time to develop a large library like that.
