### ISSUE TITLE
Playlist cannot have more than 500 videos

### ISSUE THREAD

**Issue by raphj** [iv-org/invidious#3218]
In `src/invidious/routes/playlists.cr`, there is:

```
    when "action_add_video"
      if playlist.index.size >= 500
        if redirect
          return error_template(400, "Playlist cannot have more than 500 videos")
        else
          return error_json(400, "Playlist cannot have more than 500 videos")
        end
      end
```

I do happen to need to have more than 500 videos in my playlist. What is the rationale behind this maximum? (same question for the 100 playlists per user, but I guess I will never be bothered by this)

**Comment by unixfox** [comment]
I've no idea but

This error message was introduced since the introduction of the custom playlists: https://github.com/iv-org/invidious/commit/be055d9dcb31fe64cb682d50dc70101484605741

Maybe @omarroth needed to set a limit somewhere so that people don't fill up the database by creating too many playlists.

**Comment by raphj** [comment]
Okay, so this is probably not some workaround added after seeing some bug, which was one of my first hypothesis.
 
I've compiled a version of Invidious with a limit of 10000. It's probably worth having a configuration for this. I think 500 by default is a bit low, but it could be the default value.

I think I could provide a merge request if nobody is in a rush.

What do you think?

**Comment by unixfox** [comment]
Does it work if you fill up a playlist with more than 500 videos with your modified invidious? Could be due to a size limit for the index column in the playlist table: https://github.com/iv-org/invidious/blob/master/config/sql/playlists.sql#L26

But I'm not sure if that's really true.

**Comment by raphj** [comment]
501 works, I've yet to try with more. I'll report back. Indeed we need to make sure it works with more than 255.

**Comment by SamantazFox** [comment]
This limit is probably here because of the way playlists are stored in the DB.

Playlist are currently stored in two parts: the videos are stored with unique IDs in the `playlist_videos` table, and the playlist itself (name, description, etc..) is stored in `playlists`. That playlist (in the `playlists` table) contains an array that refers to the unique IDs in `playlist_videos`.

This has to be changed, as arrays in postgres don't scale well.

On a single user instance, it won't be an issue, but on big instances, a large playlist could easily hammer the DB.
