### ISSUE TITLE
[Bug] Generic Html Injection 

### ISSUE THREAD

**Issue by a5414k5** [iv-org/invidious#3233]
Just a generic html injection, props to invidious for fixing it, 

**Describe the bug**
Generic html injections that lets the user redirect himself to any website or inject any tags.

Any browser, +  Any OS.

**Comment by TheFrenchGhosty** [comment]
For those reading, it has been fixed in https://github.com/iv-org/invidious/pull/3205

**Comment by SamantazFox** [comment]
I think we can close this by now?
(a.k.a publish the details and provide a reward)

**Comment by unixfox** [comment]
@TheFrenchGhosty can you disclose the details

**Comment by unixfox** [comment]
I don't have much time right now so I'll explain very quickly the vulnerability.

Basically if the username contained some HTML code, this HTML code was evaluated by the browser because Invidious didn't escape them. That was fixed in https://github.com/iv-org/invidious/pull/3205

**Comment by SamantazFox** [comment]
@a5414k5 you tried to contact me through IRC, right?
I've always a client running on there, if you want. I generally respond in the evening, UTC+2 time.

Otherwise, we can be reached by email at the address(es) on our website, or the ones in our Github profiles.
You can get our PGP keys from github too. E.g: https://github.com/SamantazFox.gpg
