### ISSUE TITLE
[Bug] Why do I have to put local=true?

### ISSUE THREAD

**Issue by AyaanZaveri** [iv-org/invidious#3289]
When I'm using the `/videos/:ID` endpoint, I'm given a `dashUrl`. When I try the `dashUrl` on testing websites like:
https://videojs.github.io/videojs-contrib-dash/
https://bitmovin.com/demos/stream-test
https://players.akamai.com/players/dashjs

It doesn't seem to load. 
Although, when I put `?local=true` at the end it seems to work.

The only difference I found in the manifest files between the two is the `<BaseURL>` tags.
![Screen Shot 2022-08-29 at 1 24 23 PM](https://user-images.githubusercontent.com/63752541/187260889-5651bf1e-658f-4a1a-a5e7-e5de3f1e836a.png)
![Screen Shot 2022-08-29 at 1 24 43 PM](https://user-images.githubusercontent.com/63752541/187260893-72ec6696-4e4a-4054-a91c-63f7455b9957.png)

The `?local=true` has `/videoplayback?`, whereas the `dashUrl` given has the `host` + `/videoplayback?`.

When I tried opening the link from the `<BaseURL>` with the host included, it was a valid link and played. But when I try inputting the `dashUrl` it doesn't seem to load.

Why is that?

**Comment by unixfox** [comment]
Some videos are tied to the IP address of the invidious instance so that's why `local=true` is here to load the video stream through the server of the instance. Not all videos are like this though, some will load fine without going through the server of the instance.

This is a requirement by YouTube which we can't change.

Dash by default always goes through the server of the instance so there is no parameter `local=true`.
