### ISSUE TITLE
[Question] Invidious dashUrl not working on Shaka Player

### ISSUE THREAD

**Issue by AyaanZaveri** [iv-org/invidious#3292]
### Shaka Player Error from the [Demo Website](https://shaka-player-demo.appspot.com/demo/):
<img width="1440" alt="Screen Shot 2022-08-30 at 9 40 52 PM" src="https://user-images.githubusercontent.com/63752541/187574226-3c02a74e-7fb7-4751-aab8-ae701f4cea93.png">

On websites like:
https://www.theoplayer.com/test-your-stream-hls-dash-hesp
https://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html
https://videojs.github.io/videojs-contrib-dash/

The dash stream works just fine (including the `local=true` parameter). But when I use Shaka Player it seems to throw errors.

**Comment by unixfox** [comment]
Shaka probably doesn't support the dash format provided by Invidious because invidious only support videojs, I don't know. 

Look at the console tab in the devtools for any errors.

Closing as it's unrelated to Invidious but we have had some idea to implement shaka into invidious though: https://github.com/iv-org/invidious/issues/3241#issuecomment-1206776445

**Comment by cyberpunkbln** [comment]
Hello,
is a dash.mpd not an industry standard? At my installation the url in the dash.mpd file is not correct? Correctly the <baseUrl> must pointing on an existing url that i can call in an browser (likely encoded or decoded) that doen't matter.??? Url is not the same adaptiveformats->url.
