### ISSUE TITLE
Allow iFrame

### ISSUE THREAD

**Issue by Sommerwiesel** [iv-org/invidious#3459]
The old solution to allow iframe embedding:

> add
> `proxy_hide_header "x-frame-origins";`
> to your nginx config.
>  
> _Originally posted by @FireMasterK in https://github.com/iv-org/invidious/issues/1661#issuecomment-759310622_

doesn't work. 
x-frame-options (x-frame-origins like posted above is totally wrong btw it should have been **options** not **origins**) are (mostly, on modern browsers) made obsolete by the new Content-Security-Policy headers: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

Compatibility chart for content-security-policy frame ancestors:
![image](https://user-images.githubusercontent.com/106014757/205089677-f11b9bf9-4690-4c12-98fc-a13368f53c37.png)

Invidious already uses the new Content-Security-Policy headers and thus, those need to be changed as well (replace domain.example in the frame-ancestors value):

```
proxy_hide_header x-frame-options;
proxy_hide_header content-security-policy;
add_header content-security-policy "default-src 'none'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self'; manifest-src 'self'; media-src 'self' blob: https://*.googlevideo.com:443 https://*.youtube.com:443; child-src 'self' blob:; frame-src 'self'; frame-ancestors https://domain.example";
```

I created this issue because search engine queries for "invidious allow iframe" still show the old issue with its solution as the first search  result. The old solution however doesn't work.

**Comment by Sommerwiesel** [comment]
Hey unifox, please feel free to do so :)

**Comment by unixfox** [comment]
The issue though is that it's not recommended at all to override the content-security-policy because we may need to add more parameters in it in the future and by essentially doing that you are potentially introducing a future breaking change in your instance.

I've corrected the comment from FireMasterK to `x-frame-options` but I think there should be a way not override the CSP header with a fixed value. Maybe through some NGINX regex?

But if you are adding some iframe to invidious you are modifying the source code right? Maybe you should change the CSP header in the source code of invidious instead then. This way if we change the CSP header you will notice it.

**Comment by AndresDevvv** [comment]
Is there a way to do this with a reverse proxy and just invidious standalone?

**Comment by AndresDevvv** [comment]
never mind i found a way!
