### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by dimqua** [iv-org/invidious#349]
In addition to the history of watched videos, a possibility to keep the history of search queries can be implemented. In the future, this information can potentially be useful for generation of personalized recommendations, for instance. Just like YouTube does.

**Comment by elypter** [comment]
but please make it optional or a different kind of suggestion because people usually only like some of the things they search and only search some of the things they usually watch. that can skey things a lot if the user watches some kind of stuff only by their subscriptions, external links and related videos and only searches for things that are of temporary interest or part of a research. people tend to search things they do not know more than the things they already have subscribed to.
