### ISSUE TITLE
Video plays in browser but gets 403 via API

### ISSUE THREAD

**Issue by forthrin** [iv-org/invidious#3503]
**Describe the bug**

Browsed through similar 403 issues here, but can't figure out what is the core issue or how to resolve this.

Works fine when getting directly from YouTube using [this technique](https://code.videolan.org/videolan/vlc/-/issues/26174#note_286445).

**Steps to Reproduce**

`https://invidious.weblibre.org/watch?v=GA7Kl7XWOmM` plays fine in browser, but fails through API:

```
$ ffmpeg -i $(curl 'https:/invidious.weblibre.org/api/v1/videos/GA7Kl7XWOmM' | jq -r '.formatStreams[-1].url') -c copy foo.mp4
HTTP error 403 Forbidden
```

By comparison, a video like `dP4kXJ92Qh4` works fine via the API.

**Additional context**

```
macOS 12.6
ffmpeg git-2022-06-01-c6364b71 
```

**Comment by unixfox** [comment]
This video `GA7Kl7XWOmM` is an encrypted content that can only be loaded from the same IP address as the one that generated the request for getting the content. In this case, only the server `invidious.weblibre.org` can load the content.

So you need to proxy the content through the invidious instance in order to have the video working.

You can easily do that with the special endpoint `/latest_version` like this: https://invidious.weblibre.org/latest_version?id=GA7Kl7XWOmM&itag=22&local=true

The parameter `local=true` means proxying the content through the invidious instance.
