### ISSUE TITLE
Is there a userscript that attempts to maintain user level preferences across public instances?

### ISSUE THREAD

**Issue by Jaladhjin** [iv-org/invidious#3509]
Hello!

1 very small issue I've ran into as a user of public instances is my preferences don't save across instances as I switch.

Things like auto play being the biggest 1 so I can change it per instance I run but that admittedly gets annoying after the 1st 5 or so instances people are gracious enough to share.

Does or could a userscript exist to attempt to solve this?

Thanks!

**Comment by unixfox** [comment]
Use privacy redirect or libreddit or follow this documentation page: https://github.com/iv-org/documentation/blob/master/docs/redirector-setup.md

**Comment by MintMain21** [comment]
@Jaladhjin 

https://github.com/MintMain21/Invidious-URL-Parameters-Userscript

**Comment by static000** [comment]
[This](https://greasyfork.org/en/scripts/459970-persistent-invidious-settings) is an alternative to MintMain21's solution, that I use - it has an advantage of being able to edit settings through the "official" Invidious menu.

**Comment by MintMain21** [comment]
@static000 

If I'm not mistaken, your script uses cookies. 

Mine, on the other hand, uses URL redirection.

**Comment by static000** [comment]
From my understanding (as I'm not the author), the script I linked uses cookies only to read the preferences, which are then stored in extension's internal storage. Because of that, settings persist even after clearing cookies.

**Comment by MintMain21** [comment]
@static000 

See, the thing is persistent cookies is the obvious solution, but all my attempts to enforce it in private browsing sessions have proven buggy at best. 

It's what the old "unify settings" option in Libredirect did, and it's what I tried to enforce using a cookie manager extension. 

Maybe that script does it right, but I think URL Parameters are the safest option, which is why my script does that instead.
