### ISSUE TITLE
[Bug] Tab title is different than video

### ISSUE THREAD

**Issue by marcin93** [iv-org/invidious#3512]
**Describe the bug**
One of few movies opened via Ctrl+Click to be seen later will have different **tab** title than movie it self.

**Steps to Reproduce**
This is no easy reproducible. Happens  from time to time - maybe I'm not only one.
0. use Firefox
1. Go to 'Subscriptions'/List of films on some channel eg: /channel/UCLBx0xIydDmgreeALWNb0bg
2. Ctrl+Click on 'Any title' 
3. Keep opening few other titles 
4. One/Few from opened in background tabs will have different title than video

**Screenshots**
![Screenshot_2022-12-22](https://user-images.githubusercontent.com/3214139/209198825-92a676d4-5a9d-4ae4-bf6e-555b81400aea.png)

**Additional context**
 - Browser (if applicable): Firefox 108 (happen on older as well)
 - OS (if applicable): seen that on OSX and Linux

**Comment by unixfox** [comment]
Can reproduce the issue and no idea why that happen, it's really strange.

**Comment by 11Tuvork28** [comment]
Yeah it was happening because requests were bleeding into each other so to speak, sometimes entire parts of a given template wouldn't be rendered, under high load on a single replica > 100 connections.
Solvable by upping the replica count...
Should be closed as its nothing related to invidious but to the language/kemal itselft. Should be documented in my opinion.

**Comment by marcin93** [comment]
Thanks @11Tuvork28 for explanation. Indeed this can be most likely seen as overload on instance. Also having such point in administrative documentation would be good.
