### ISSUE TITLE
Add Sponsorblock?

### ISSUE THREAD

**Issue by steviesteve919** [iv-org/invidious#3519]
If we're gonna block the ads, may as well block sponsors too.

**Comment by unixfox** [comment]
The official sponsorblock extension support invidious.

**Comment by steviesteve919** [comment]
> The official sponsorblock extension support invidious.

No, can Invidious block sponsors by default?

**Comment by unixfox** [comment]
no thats not planned

**Comment by mattogodoy** [comment]
I came looking for the same. I know it's supported by the extension, but it would be great to have it embedded. iPhones, for instance, don't have the ability to use extensions in any browser.

**Comment by cazwacki** [comment]
I will add to @mattogodoy 's sentiment. I self-host Invidious and while SponsorBlock works on my desktop, I primarily browse it using my Android device. You can install SponsorBlock on custom browsers, but the 3rd-party sites option cant be enabled due to the extra permissions it requests. It would be great to have SponsorBlock functionality on other devices.

**Comment by yagarea** [comment]
There is browser plugin that skips sponsor segments in videos called sponsor block and it has a open API: [wiki.sponsor.ajay.app/w/API_Docs](https://wiki.sponsor.ajay.app/w/API_Docs)

**Comment by unixfox** [comment]
> There is browser plugin that skips sponsor segments in videos called sponsor block and it has a open API: [wiki.sponsor.ajay.app/w/API_Docs](https://wiki.sponsor.ajay.app/w/API_Docs)

we know, the official extension literally support invidious...

**Comment by hiatsu0** [comment]
I’d love deeper integration of SponsorBlock into Invidious as well because on mobile and on my smart TV there is no way (that I can think of) to use the extension. And these cover about 95% of my use. 

For mobile there is a native app to use Invidious that has SB integrated but the performance & usability are not that great. Much prefer to use the web UI.

**Comment by Berkopl** [comment]
> I’d love deeper integration of SponsorBlock into Invidious as well because on mobile and on my smart TV there is no way (that I can think of) to use the extension. And these cover about 95% of my use.
> 
> For mobile there is a native app to use Invidious that has SB integrated but the performance & usability are not that great. Much prefer to use the web UI.

Me to waiting for sponsor block like in viewtube.io
