### ISSUE TITLE
[Question] feed/popular shows vids from subscriptions when logged out

### ISSUE THREAD

**Issue by tlc** [iv-org/invidious#3577]
I am running invidious at home.  I have a single account and uploaded my subscriptions to it.  I am the only user so far.

I was surprised to notice that when logged out and using Private Browsing mode, the feed/popular page was the same as when I was logged in and is based on 

1. viewing from the only account, and 
2. subscriptions from the only account (even subs I haven't watched anything from)

I haven't used invidous that much yet, and there are definitely things on that page from channels I'm subscribed to, but from which I haven't watched _any_ vids yet on invidious.

If I was providing a service to a large number of people, I could see that a "Popular" page based on actual viewing might be a good thing.  **But serving a small number of people, I want more privacy -- no knowledge of what's popular with other users.   IMHO, when logged out feed/popular should either be disabled or based on youtube.com usage.  And user X's viewing should not affect user Y's pages either.**

The feed/trending page doesn't resemble anything I've watched.  IMHO, the same logic that caused that to not be based on local usage applies to feed/popular.

Beyond that, I don't know why vids that have never been watched on my invidious instance, from subscriptions I've never watched on my invidious would be considered "Popular".

**Comment by unixfox** [comment]
Feel free to disable the popular page if you don't want it: https://github.com/iv-org/invidious/blob/master/config/config.example.yml#L219

The videos that appears on the popular page are obviously from your subscriptions because it's taking the channels that the users subscribed to. See https://docs.invidious.io/faq/#table-of-contents

We won't disable by default the popular page for low usage instances because there are people that are using invidious locally and like the popular page.
