### ISSUE TITLE
[Bug] AZERTY keyboards 1-9 hotkeys

### ISSUE THREAD

**Issue by PhilJbt** [iv-org/invidious#3875]
**Describe the bug**
`1-9` hotkeys (skipping to 10% through 90% of a video) on AZERTY keyboards require to keep `Shift` pressed, which is technically logical but unpleasant from the user's point of view. For example, the Youtube website does not require to keep `Shift` pressed.
Also, `1-9`  numpad keys seem not to be binded.

**Additional context**
 - Browser: Firefox 114.0 (64 bits)
 - OS: Windows 10
 - Instance: invidious.fdn.fr

**Comment by SamantazFox** [comment]
Regarding 1 to 9 on the top row of the keyboard, I'd prefer to not change that. It's currently relying on key codes, rather than key position, so changing that would mean changing all the shortcuts code, which I'm worried to do (as the saying says: "never try to fix something that is working").

Regarding the numbers on the numpad, that's intentional. I've removed it because multiple users complained that they pressed `0` or `1` by mistake instead of the right arrow (due to the close proximity of those key on some keyboards) which made them lose the watch progression.
