### ISSUE TITLE
[Bug] Index out of bound when trying to import YouTube subscriptions list

### ISSUE THREAD

**Issue by Fluidetom** [iv-org/invidious#4140]
**Describe the bug**

When trying to import my exported YouTube subscriptions, I get an "index out of bound" error message.
I tried multiple times on different instances and always got the same error.

**Steps to Reproduce**

1. I followed these steps to export my YouTube subscriptions : https://docs.invidious.io/export-youtube-subscriptions/
2. Then once logged in Invidious, i went into subscriptions -> manage subscriptions , then import/export
3. Click on _Browse _beside "Import YouTube playlist (.csv)"
4. Click on Import

**Logs**

`Title: `Index out of bounds (IndexError)`
Date: `2023-10-02T20:04:43Z`
Route: `/data_control?referer=%2Ffeed%2Fsubscriptions`
Version: `2023.09.24-473622e3 @ master`

<details>
<summary>Backtrace</summary>
<p>
   
```
Index out of bounds (IndexError)
  from /usr/share/crystal/src/http/formdata.cr:121:11 in 'update_data_control'
  from lib/kemal/src/kemal/route.cr:12:9 in '->'
  from src/invidious/helpers/handlers.cr:30:37 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from lib/kemal/src/kemal/filter_handler.cr:21:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:94:12 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/invidious/helpers/handlers.cr:151:29 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call_next'
  from src/ext/kemal_static_file_handler.cr:112:11 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/handler.cr:28:7 in 'call'
  from /usr/share/crystal/src/http/server/request_processor.cr:51:11 in 'process'
  from /usr/share/crystal/src/http/server.cr:500:5 in '->'
  from /usr/share/crystal/src/fiber.cr:146:11 in 'run'
  from ???
```
</p>
</details>`

**Additional context**

Firefox 117.0.1 (64-bit) on Linux Mint

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/4069

**Comment by ihave1000usernames** [comment]
I found a workaround that might help other people experiencing this problem:

I found this via [Reddit ](https://www.reddit.com/r/rss/comments/l3x6e8/youtube_subscriptions_opml_2021/). Go to [this link] (https://greasyfork.org/fr/scripts/418574-export-youtube-subscriptions-to-rss-opml), add the browser extension listed (I used Tampermonkey), ensured it was installed, then went to the Youtube subscriptions page, then at first I immediately went up to the addon and told it to "export youtube subscriptions to OPML" and it did. I imported THAT file into Invidious using the "[Import YouTube/OPML subscriptions]"(https://github.com/iv-org/documentation/blob/master/docs/export-youtube-subscriptions.md) option with that file but found out it did NOT grab all of them. I had to go back and manually scroll down the page so that it would populate all of my subscriptions onto the page. Then re-export it then re-import that new file. It worked.
