### ISSUE TITLE
[Feature request] Allow to show absolute date

### ISSUE THREAD

**Issue by gqqnbig** [iv-org/invidious#4165]
**Is your feature request related to a problem? Please describe.**

When I search videos or skim videos in a channel, Youtube shows a relative date for each video, so as Invidious. I would like to know the exact date.

In particular, old videos were all uploaded, eg. "2 years ago", but I need to quickly know exactly which day.

![chrome_2023-10-13_22-38-09](https://github.com/iv-org/invidious/assets/614159/5c383f64-821f-4ae3-9614-45ec8b3a4ba9)

Certainly some people like relative dates. We can make an option for users to switch.

**Comment by unixfox** [comment]
Makes sense. I think this should be included in a tooltip when hovering the mouse over the date.

Seems like a very simple change, @gqqnbig do you want to contribute to adding this new feature?

**Comment by gqqnbig** [comment]
Thanks for the acknowledgement but I don't have time for this project right now. If there is a commit, sometimes I'm able to help test it.

**Comment by SamantazFox** [comment]
Unfortunately, that can't be fixed. Youtube only returns a text string in the form `{span} ago` for the `browse` and `search` endpoints, which are used to display the various channel pages, playlists and search results.

The exact publication date is only available on the `player` endpoint, which is used on the watch page.

The reason we can't request that `player` endpoint elsewhere is because it has to be queried for each individual video. So obviously we can't do 20/30/100 queries (depending on the page) to google for each page displayed. That doesn't scale well and would destroy performance on large instances.

Related: https://github.com/iv-org/invidious/pull/3968#discussion_r1253508149 (In our case, privacy is not really a concern, as Youtube already knows what it returned, e.g in search results or a channel page).
