### ISSUE TITLE
[Bug]  HTTPS don't work (docker)

### ISSUE THREAD

**Issue by bronzetuxie** [iv-org/invidious#4459]
**Describe the bug**
Cannot use my invidious on HTTPS self hosted instance using docker. HTTP works fine, but HTTPS return error code: SSL_ERROR_RX_RECORD_TOO_LONG.

I have used the default docker compose from docs, without changing anything.

**Comment by unixfox** [comment]
Hello,

For these types of not so specific to invidious. I would suggest asking on the matrix room (https://matrix.to/#/#invidious:matrix.org) or IRC channel (https://web.libera.chat/?channel=#invidious).

I'm going to close this issue because the invidious maintainers do not have time to reply to your question not specifically related to invidious, but a more general networking question.
