### ISSUE TITLE
[Bug] Invidios behind Authelia + NPM results in Error 500 on the second page of any channel

### ISSUE THREAD

**Issue by Mr-Boshi** [iv-org/invidious#4469]
**Describe the bug**
I have a NGINX Proxy Manager as a reverse proxy and Authelia as a sign-in gate and Invidios. Everything is in Docker. In this configuration _almost_ everything works but there is a very annoyng thing: if I open a channel page, scroll down and click "Next page" button I get Error 500. If i remove the Authelia out of the mix, everything works just fine.

**Steps to Reproduce**
1. Setup Authelia and NPM according to the guides.
2. Setup reverse proxy config for Invidios instance.
3. Add settings for authelia auth control in the Advanced tab according to the [documentation](https://www.authelia.com/integration/proxies/nginx-proxy-manager/#protected-application).
4. Open any channel page, scroll down and click "Next page".

**Logs**
Nothing appears in the logs.

I think it is the proxy problem but I hope the experts in the Invidios will help to find the reason and to tweak the config so it works fine.

**Comment by unixfox** [comment]
Hello,

For these types of not so specific to invidious. I would suggest asking on the matrix room (https://matrix.to/#/#invidious:matrix.org) or IRC channel (https://web.libera.chat/?channel=#invidious).

I'm going to close this issue because the invidious maintainers do not have time to reply to your question not specifically related to invidious, but a more general networking question.
