### ISSUE TITLE
[Bug] API ignoring field parameter

### ISSUE THREAD

**Issue by sean89503** [iv-org/invidious#4579]
**Describe the bug**
When using the api it is stated in the[ doc](https://docs.invidious.io/api/) it will support the [fields API](https://developers.google.com/youtube/v3/getting-started#fields)

**Steps to Reproduce**
in python
```
import` requests
from urllib.parse import parse_qs

# Define the API endpoint
api_endpoint = "https://invidious.us/api/v1/channels/UC8i8e7likh-EYMq1bZ0ttHw"

# Define the desired fields
desired_fields = ["fields", "author", "authorId"]

# Construct the query string
query_string = "&".join([f"{field}=" for field in desired_fields])

# Append the query string to the API endpoint
url = f"{api_endpoint}?{query_string}"

# Make the GET request
response = requests.get(url)

# Check if the request was successful (status code 200)
if response.status_code == 200:
    # Parse the JSON response
    data = response.json()
    # Print the relevant fields
    print("Author:", data.get("author"))
    print("ALL LOOKS:", data.get("authorId"))
else:
    print("Error:", response.status_code)

```
please **change invidious.us** as that's a redirect site
-->

**Screenshots**
![image](https://github.com/iv-org/invidious/assets/22017525/0705db6c-dc26-4f0e-be14-abf42a5c7e1d)

**Comment by unixfox** [comment]
fields feature were removed in https://github.com/iv-org/invidious/pull/4276

doc is outdated :/ @SamantazFox

**Comment by absidue** [comment]
@unixfox There is already a PR open to update the docs, all you need to do is review it :)

**Comment by sean89503** [comment]
is there a way to get only a few items, most of the info I want is in /api/v1/CHANNELS/videos but the description of the videos are cut off in /api/v1/CHANNELS/videos so I have to go to /api/v1/videos/video_id to get it but I have to download everything.

**Comment by SamantazFox** [comment]
> is there a way to get only a few items

@sean89503 We removed that `fields` feature because it was slowing down our API due to extra processing on the server side. Even if we only returned a single field, invidious had to parse the full data from Youtube, generate a full response, then drop the other fields.

In addition, the full response is small enough (~60kB or less than 10kB compressed) for it to not be a problem.

> the description of the videos are cut off in /api/v1/CHANNELS/videos so I have to go to /api/v1/videos/video_id to get it but I have to download everything.

Blame Youtube for that. The full description is only available from the `/api/v1/videos` endpoint. All other places get a truncated (and un-formatted) version.
