### ISSUE TITLE
Default settings should be optimized

### ISSUE THREAD

**Issue by gloschtla** [iv-org/invidious#460]
invidio.us was presented as data-saving youtube interface. But when I check the [settings](https://www.invidio.us/preferences?referer=%2Ffeed%2Ftrending), it appears that invidio.us plays videos in HD resolution by default, even though I was on my mobile device.

Would it not make sense to change some of the default settings? I suggest:
_Proxy videos_: Yes, and please with an IP of my region.
_Preferred video quality_ depending on visitor's display resolution.
_Player volume_ 65% by default.
_Default captions_ depending on my locale

**Comment by cyaniventer** [comment]
> Proxy videos: Yes, and please with an IP of my region.

Not a good idea because most people use the defaults and would never look at settings which means more load for invidio.us and about that with an IP of my region thing, that is not going to happen anytime soon - it will proxy through invidio.us ip. buying a ip for every region is insanity and why would you want that anyways?

> Player volume 65% by default.
Again very bad idea, why would you want to do that? If you want to lower the volume then you can already do so by changing your device's volume.

Also you have to change your preferences only once so what's the issue with defaults?

> Preferred video quality depending on visitor's display resolution.
> Default captions depending on my locale

imo these two make some sense.

**Comment by omarroth** [comment]
> Proxy videos: Yes, and please with an IP of my region.
 
See my comment in [#453](https://github.com/omarroth/invidious/issues/453#issuecomment-477574597). Proxying videos from the instance itself should fix the issue that is being addressed here.

> Player volume 65% by default.

I'm having trouble seeing the logic here. If the goal is to make the site lightweight I'm not sure how changing the player volume helps accomplish this. Is there some other way this optimizes the site that I am missing?

> Preferred video quality depending on visitor's resolution.

This requires some way of detecting the visitor's resolution as well as additional logic for changing qualities. My main concern here is that I would consider this a form of tracking/fingerprinting and would require JS.

> Default captions depending on my locale

I'm wary of doing this since it would require automatically changing other user preferences.

**Comment by elypter** [comment]
>Player volume 65% by default.

i never understood this when a website did that. if you tone down the digital amplitude this means you need a higher volume on your speakers and the amplifyers in the chain before. all this amplification creates noise and signal degradation. the digital volume should always be at 100% unless you have already turned down the volmes later in the chain as low as possible and you want it even more silent.
