### ISSUE TITLE
[Feature request] Video cache

### ISSUE THREAD

**Issue by mooleshacat** [iv-org/invidious#4903]
**Is your feature request related to a problem? Please describe.**
No. Just an idea that may help with busy public instances.

**Describe the solution you'd like**

Video caching on disk. Ability to limit size. Prioritize by busiest videos (least busy video gets pruned if too large).

**Describe alternatives you've considered**

considered yt, but liking invidious much more 👍 

**Additional context**

I think this feature would be good for those with some disk space, and who run busy / public instances

**Comment by Fijxu** [comment]
Sound cool, but IMO this will not be useful to reduce the load of public instances.
Why? Because there is a lot of people watching different videos, so if invidious caches a video in disk, that video will be fetched by only a very small percent of the people using the instances.
This could work for videos on the popular page.
