### ISSUE TITLE
[Bug] "This helps protect our community."

### ISSUE THREAD

**Issue by NolonQ** [iv-org/invidious#4908]
**Describe the bug**

This https://github.com/iv-org/invidious/issues/4734 is happening again on nearly all instances.
FUCK GOOGLE
**Steps to Reproduce**

**Logs**

**Screenshots**

**Additional context**

**Comment by warioishere** [comment]
same here :(

**Comment by ggtylerr** [comment]
A/B test so not all instances are affected yet, but yes, unfortunately there's another block. With that said, this is a duplicate issue.

**Comment by MMaster** [comment]
> With that said, this is a duplicate issue
Duplicate issue of issue that has last comment stating the solution was released and any more comments disallowed from anyone except for collaborators (and yeah that solution worked for weeks).

I think its completely fine to report that this happens again since this is basically new issue with the same symptoms. Just because YT returns the same error string doesn't mean its the same reason. 
Keeping it all under the same issue (and even locking the discussion) may be quite counter-productive as google will keep changing things and it will be 1 huge issue spanning months and years containing 10s - 100s of changes. But that's just my 2 cents.

**Comment by hix1000** [comment]
I'm seeing the same thing but it's instead saying "This video may be inappropriate for some users."

**Comment by ggtylerr** [comment]
> I think its completely fine to report that this happens again since this is basically new issue with the same symptoms. Just because YT returns the same error string doesn't mean its the same reason. 

That is fair, but it's nearly identical, the only difference being that the patch previously made no longer works. Not to mention, creating new issues only increases bloat, and the devs are already aware of the block.

Making a "master" issue per se to track blocks would honestly work best - all that's needed is to update the OP and have the comments act as a changelog. Much better than having a ton of separate issues all for the same thing, which is just another attempt by Google to block Invidious.
