### ISSUE TITLE
sql backup

### ISSUE THREAD

**Issue by theScrabi** [iv-org/invidious#506]
Sometimes tables can be broken, this is why for a mysql docker installation i always also have a backup directory where the mysql/mariadb container is using a backup volume where sql files are automatically stored. Could such a backup be introduced to the docker installation, or is this even necessary for postgress?

**Comment by omarroth** [comment]
Anecdotally, I have yet to encounter any issues with Postgres w.r.t any form of corruption. I would be very interested though in any comparisons/data between Postgres and other databases on how common corruption is and how well they are able to recover.

I would generally consider this out of scope, since I trust administrators to know how best to handle backups for their configuration, and would rather not handle recovery automatically. Also to note is that [Invidious-Updater](https://github.com/tmiland/Invidious-Updater) provides options for backing up and restoring database changes, although I don't believe it supports backup for docker instances.

I would be very interested in how other projects handle this, and any thoughts from @tmiland on whether or how backup should be integrated into Invidious itself.

**Comment by tmiland** [comment]
I think for Docker, it would be easier to take a snapshot of the invidious_postgres_1 container.

[Docker container: Backup and Recovery ](https://linuxconfig.org/docker-container-backup-and-recovery)

As for integration into Invidious, a simple config option true/false to store a dump in a backup folder would be a good idea, possibly on shutdown or daily/weekly etc...

Restoration i guess would make most sense to be handled manually, to avoid the responsibility for data-loss.

[Invidious-Updater](https://github.com/tmiland/Invidious-Updater) only handles manual backups. 

Option 8 set's up the backup scripts from [pgbackup](https://github.com/tmiland/pgbackup). 

A cron job can then be set up like so: 

`crontab -e`

`@daily bash /path/to/pgbackup/pg_backup.sh > /dev/null 2>&1 #Automated PostgreSQL Backup on Linux`

This will back up all db's on the pgsql server on a daily schedule, using config options in [pg_backup.conf](https://github.com/tmiland/pgbackup/blob/master/pg_backup.conf)
