### ISSUE TITLE
Issues & question about features

### ISSUE THREAD

**Issue by ajpanton** [iv-org/invidious#5099]
There doesn't seem to be a place to ask for help, so not sure if this is an appropriate place for this.

Been struggling to get a self-hosted instance of this working. Firefox complains about violating "script-src 'self'", Chrome gives 403 errors, and I can't figure out how to proceed.

I also noticed that a few key features might be missing, which makes me want to give up on this. What is the status on the following features? Might they get implemented at some point, or is there no interest at all, or do they already exist and I'm being blind?
- A way to prevent outsiders of using my service without an account.
- Chapters.
- A way to watch age restricted videos.

**Comment by syeopite** [comment]
You should go into the matrix room for help with installing and setting up Invidious

https://matrix.to/#/#invidious:matrix.org

For private invidious instances there is a feature request #446 but the method suggested by us maintainers is to just use an HTTP auth.

Chapters support is tracked in #2395 and there is an already pending pull request to add the feature.

As for age restricted videos well... Invidious used to be able to play them but now YouTube has removed all known methods of playing them without a YouTube account. So that feature cannot be reimplemented now...
