### ISSUE TITLE
Default to DASH when googlevideo.com can’t be reached.

### ISSUE THREAD

**Issue by shortenjukebox** [iv-org/invidious#512]
If `googlevideo.com` is blocked, the video player breaks and is inoperable. This makes it impossible for people who could otherwise use the Invidious instance’s servers as a proxy (with DASH) to watch videos.

**Comment by Perflyst** [comment]
Do not use dash as "proxy option", you should use local=true instead.

**Comment by johnwmail** [comment]
Hi, is it dash == proxy (local=true)?
what is different dash and "proxy option"?
thanks.

**Comment by omarroth** [comment]
Appears to be a duplicate of #425. Currently I consider DASH a beta feature, which is why it's opt-in. Although as mentioned above I believe the desired behavior is for `local=true` to be enabled by default.

`local=true` is enabled by default for the official hidden services, but is not for https://invidio.us as it's more bandwidth intensive. Rollout has been quite slow to ensure that any potential issues can be addressed. See [here](https://github.com/omarroth/invidious/issues/177#issuecomment-423703354) for more info.

@johnwmail [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP) is a streaming technique used by YouTube to provide resolutions higher than 1080p. Very simply: it provides multiple files for a client to use depending on network, user preference, etc. I would very much recommend reading my comment [here](https://github.com/omarroth/invidious/issues/177#issuecomment-423843512) for more info. All streams used by DASH *must* be proxied in order for them to work, and why `quality=dash` has been recommended previously as a solution for #92.

The current recommended solution is to use `local=true`, as it ensures that all files used by the player are proxied.

`quality=dash`: proxies streams used for dash, but not the default 720p, medium, etc (see #389)
`local=true`: proxies 720p, medium, etc

`local=true` does not have to be enabled for dash to work, as dash will automatically proxy everything it needs.

**Comment by johnwmail** [comment]
Hi, I understand what is different "dash & proxy" now,
But I still do not understand, what is the disadvantage use dash (even as default)?
Since dash will automatic "provides multiple files for a client to use depending on network, user preference".

**Comment by omarroth** [comment]
Main disadvantages of using dash by default are mentioned [here](https://github.com/omarroth/invidious/issues/425#issuecomment-487385499):
> Dash currently has minor issues with playback (see #193) and is more bandwidth intensive for the site. Both of these issues are being worked on, but I currently don't consider it stable enough to have enabled by default or as fallback.

**Comment by johnwmail** [comment]
> Main disadvantages of using dash by default are mentioned [here](https://github.com/omarroth/invidious/issues/425#issuecomment-487385499):
> 
> > Dash currently has minor issues with playback (see #193) and is more bandwidth intensive for the site. Both of these issues are being worked on, but I currently don't consider it stable enough to have enabled by default or as fallback.

For example, this link only work with dash, and NOT work with hd720(default)
https://invidio.us/watch?v=PX-zAEOM-as

**Comment by johnwmail** [comment]
Hi, is it possible, make "quality" configurable on config/config.yml?
Thanks.

**Comment by omarroth** [comment]
```yml
default_user_preferences:
    quality: "dash"
```

See #415, also just added to the [wiki](https://github.com/omarroth/invidious/wiki/Configuration).

**Comment by johnwmail** [comment]
> ```yaml
> default_user_preferences:
>     quality: "dash"
> ```
> 
> See #415, also just added to the [wiki](https://github.com/omarroth/invidious/wiki/Configuration).

I see now, thanks.
