### ISSUE TITLE
[Bug] Incorrect audio language

### ISSUE THREAD

**Issue by privacyadmin** [iv-org/invidious#5121]
Invidious is set to English for interface and subtitles but for some reason, the audio in some videos are not downloaded in English even though they are in English speaking videos.

**Comment by privacyadmin** [comment]
I see a lot of users also experiencing the same issue but they are commented in closed tickets. I hope the devs are made aware of this audio issue.

Thank you

**Comment by unixfox** [comment]
https://github.com/iv-org/invidious/issues/2007

**Comment by ktfcaptain** [comment]
I thought I was done configuring things after a really rough time with all this and the audio won't stay in english.  I have manually set US and/or English everywhere possible and the video clearly displays English is the ORIGINAL audio, but videos start in spanish (i just confirmed, even tho German is the first option).  

It might be on first load and/or new accounts because I had forgotten about it for a while then it happened again.  Just sharing info.

**Comment by kladderadeng** [comment]
I also thought this is no longer an issue. But for me nearly everything is in Spanish. All my settings are English, though and I have nothing spanish on my systems. I even tried to switch language settings from English to something else and back, because I thought maybe it's just something not set correctly within the database with the user settings, but it does not help.

From other comments I get the impression that we should be able to select the language in the video on the bottom right where we also change the resolution? If this is the case, it does not show up for me. Clearing browser caches / using in-private windows did not help also. I am a bit lost why this seems to work in Dash for many, but for some it does not and I do not know yet how to debug this :-(
