### ISSUE TITLE
Feature request: listen only for mobile/useragent only

### ISSUE THREAD

**Issue by johnwmail** [iv-org/invidious#516]
Hi, as title, is it possible add mobile mode option?
Thanks.

**Comment by elypter** [comment]
what do you want to achieve? do you want that when you are loged in and you are using a mobile browser that the video loads in audio mode? i assume you dont want to have to switch settings everytime you switch from yor desktop to your phone? wouldn't it be possible to just have 2 accounts and sync the settings occasionally?

alternatively a hybrid setting system would be possible. if invidio.us allowed to load the settings stored on the server and then override some of them by settings stored in the cookies you could have individual preferences for each device

**Comment by johnwmail** [comment]
> what do you want to achieve? do you want that when you are loged in and you are using a mobile browser that the video loads in audio mode? i assume you dont want to have to switch settings everytime you switch from yor desktop to your phone? wouldn't it be possible to just have 2 accounts and sync the settings occasionally?
Yes, than is what I want.
And yes, I did it (use two account).

**Comment by omarroth** [comment]
Invidious currently provides a `PREFS` cookie to save preferences for unregistered users (see #41).

Would it make sense to add a `Save preferences locally` to do something similar for registered users?

**Comment by johnwmail** [comment]
> Invidious currently provides a `PREFS` cookie to save preferences for unregistered users (see #41).
> 
> Would it make sense to add a `Save preferences locally` to do something similar for registered users?

Yes, absolutely.

**Comment by elypter** [comment]
i would suggest an additional settings page that represents the locally saved settings that is accessible through the regula account settings. each setting should have a checkbox in front of it that defines if the setting exists in the local cookies. cookie settings shold always override account settings if they are present.

this sounds a little more complicated but i consider this important because it avoids the confusion with unexpected sync behavior. for example:

if you save locally it could either mean: save all settings to the cookies. this would mean that these settings always override the account settings. so if you change something on another device then that will never have an effect on the device with local settings which makes it pointless to even be logged into the account at all. if you however only save what is different from the account settings then that creates other poroblems. imagine you have autoplay enabled in your account and you disable the settings on your mobile device. that setting is saved in the cookie because it is different. now you are doing a presentation on your laptop and you decide to turn it off in your account settings. a few hours later you go to the settings on your mobile to change the video quality. you hit save but then it deletes the setting from the cookie because account settings and local settings are equal. you return back to home and turn autoplay back on on your laptop to watch some videos. next day you go to work and want to look something up on your phone and the last tab you had open was an annoying or embarrasing video. this suddenly blasts through the quiet room and you are totally confused to why that happend because you never turned off autoplay on your mobile device.
