### ISSUE TITLE
Doesn't like being proxied to a subdirectory

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [iv-org/invidious#542]
I am proxying my Invidious install through Caddy, like so:
```
proxy /invidious localhost:3000
```

When both servers are up, and I access ``<my-ip>/invidious``, I get redirected to ``<my-ip>/channel/UCXZiiTe_CvWRNLbjua6Khxg``.. somehow?

Accessing the install directly works fine.

**Comment by ThatNerdyPikachu** [comment]
Any idea why this would be happening?

**Comment by omarroth** [comment]
Appears to be directing you to [this channel](https://invidio.us/api/v1/channels/Invidious?pretty=1), which has user name "Invidious".

From the above though it appears it's sending Invidious a request to `/invidious`, rather than `/`. You might take a look at [this thread](https://caddy.community/t/redirects-for-app-running-as-subfolder-behind-proxy/2816) for help rewriting your configuration (if you haven't already seen it). Unfortunately I don't know enough about Caddy to be much more help than that.

**Comment by ThatNerdyPikachu** [comment]
```
Apps that are reverse-proxied need to be able to support that; RStudio either doesn’t or isn’t configured to preserve the URI.
```

**Comment by omarroth** [comment]
My understanding is that that is in reference to the redirects provided by the application, for example logins would need to be configured to redirect from `/` to `/invidious/`. In this case the issue appears to be that Caddy is not correctly rewriting the URI it provides to the application.

**Comment by ThatNerdyPikachu** [comment]
Alright, I got the page loading (see https://i.pinged-b1nzy-for.fun/i/nl3aaahb.png
), but it's unstyled: https://i.pinged-b1nzy-for.fun/i/nl3aaahb.png, and the ``Login`` button, for example, takes me to ``/login``, instead of ``/invidious/login``

**Comment by omarroth** [comment]
Likely unstyled since it's trying to load e.g. `/css/default.css` vs. `/invidious/css/default.css`.

Apologies if it seems like your issue is being tossed back and forth. There's two very similar issues here: one with Caddy not rewriting the URLs being sent to Invidious (which now appears to be resolved), and URLs being served from Invidious not having the correct path prefix.

Since the issue your configuration appears to be resolved, mholt/caddy#2617 can likely be closed. As mentioned above and in the linked issue, Invidious needs to be able to support a path prefix. If you'd like to rename to something like "Support path prefix" or similar I'll mark this as an enhancement and take a look into adding it when I have a free moment.

**Comment by Perflyst** [comment]
Why does invidious has hardcoded /css?
why not just css/style.css without hardcoded /?

**Comment by omarroth** [comment]
Because it won't direct to the correct URL in most cases. For example when viewing `/channel/UCXZiiTe_CvWRNLbjua6Khxg`, `css/style.css` directs to `/channel/css/style.css`.

**Comment by omarroth** [comment]
You *can* use relative paths for assets, e.g. `../css/style.css`.  IMO makes more sense to support a different base instead of trying to use relative URLs. Would also appear to close #286.
