### ISSUE TITLE
Dash not working in Safari

### ISSUE THREAD

**Issue by Duckbilled** [iv-org/invidious#692]
Dash on safari (macos) starts for a few seconds till it starts loading indefinitely.

**Comment by omarroth** [comment]
Would you mind checking devtools to see if there are any errors being displayed? Can you reproduce this in another browser, or is it only an issue in Safari?

**Comment by Uffje** [comment]
I’ve checked, it gives me the following error:

 Failed to load resources: the server responded with a status of 404 (not found)

I am not sure if I am looking at the correct log though. 

Unfortunately I have a problem with Firefox and can’t test it in an other browser, but I believe it used to work before.

**Comment by Uffje** [comment]
Just realised FF works again and Invidious works as should in Firefox on Mac using Dash 1080p.

**Comment by pawi** [comment]
Tested Chromium and the issue is only with Safari on macOS.

While a 30 second video play complete with Safari anything longer (at least > 3 min tested) stops playing after second 9 or 10. No specific errors found with Safari dev tools. It looks like it just doesn't load any further videoplayback chunks.

I use dash enabled and proxy video on my personal instance.

**Comment by michaelkeuter** [comment]
I see exactly the same behaviour in the latest Safari version 13.0.4 on macOS 10.13.6.

**Comment by michaelkeuter** [comment]
Update: the same happens on the iPad (v13.2.3) and it also happens with videos that have only audio:

https://invidio.us/watch?v=1D6Y3zdOSRI

**Comment by imtbl** [comment]
I can confirm a similar behavior for both the latest iPadOS as well as the latest iOS using my self-hosted Invidious instance as well as the official one.

DASH works perfectly fine on Arch Linux( Brave), macOS (Brave) and Android (Brave and Kiwi), but on both my iPad and iPhone every video served with DASH stops after 9 seconds and seems like it’s buffering indefinitely (but never continues), regardless of the set video quality. I’ve also noticed that the audio only mode doesn’t load the video at all on iPad/iOS, it looks like it’s buffering straight away and never starts playing.

When not using DASH, all the videos play just fine on iPad/iOS, in any quality.

**Comment by lucky13820** [comment]
I always thought it was my server is not powerful enough. Damn, really wish we can fix this problem.

**Comment by Uffje** [comment]
I started using Firefox shortly after posting this and never really (just some design/feature choices) looked back. It still has some loading issues with DASH once in a while, in general a lot of things just work better.

**Comment by lucky13820** [comment]
For iOS device, you can sideload an app called Invid. It can play dash with no problem. https://github.com/cclhk/Invid

**Comment by Phantop** [comment]
I have DASH quality issues on my iPhone 6s, however DASH seems to work on my iPad. The new DASH quality settings don't help, and if DASH is enabled on an instance then the quality on my iPhone becomes terrible (I'm guessing something like 360p). Makes it very inconvenient because there's no way to use hd720 on one device and DASH on another

**Comment by Rjevski** [comment]
This is related to the following bug in Video.js: https://github.com/videojs/video.js/issues/6762

Implementing [this workaround](https://github.com/videojs/video.js/issues/6762#issuecomment-662488446) in `assets/invidious/player.js` solves the issue for now with apparently no ill effects on Safari.
