### ISSUE TITLE
Continuation link too long error

### ISSUE THREAD

**Issue by Jtasiu** [iv-org/invidious#732]
Using the API (comments) sometimes the links returned like the continuation link is too long to be considered valid. The browser returns 400 Bad Request error when trying to access the URL. Any way to fix this?

**Comment by Seneral** [comment]
I am developing my own YouTube frontend rn and noticed the same error today. Turns out that error came from my Node.js proxy server, which has a limit of 8kb for headers by default (this includes URL path itself and header data).
8kb - yes that is really the size of the continuation URL. It contains a continuation token, twice, and it grows and grows the more comments are loaded. From experience, after about 600-700 comments, the URL size becomes 8kb and that's probably where you get the error.
If Inviduous uses node.js, the just need to provide the CLI option `--max-http-header-size=65536`

This only works up until YouTubes servers themselves consider the URL too long. This happens from around 14650 bytes and the error is 413: Payload too large. The number of comments was 1500-1600, but I also tried in standard youtube (took 25mins to scroll down with an autoscroller) and then the error occured at ~1300 comments already.

So this is a design error by YouTube - and has some serious implications. It is technically impossible to load more than ~1600 comments, and I guess you could call that censoring?

**Comment by Seneral** [comment]
Ok another temporary fix:
If the token size is over a certain limit (less than half of the maximum, presumably 8kb) then only send the continuation token, not ctoken (they are exactly the same, but youtube sends both for some reason, which effectively halves the amount of comments you can technically get). Of course only do that for large tokens (when someone actually cares to scroll enough or load all comments using API) as to minimize suspicious requests to YouTube.

Additionally you can further double it (presumably) if you increase the limit on your server side, since the 400 error is definitely an error resulting from invidious servers and not from YouTubes servers (they generate a 413)

So theoretical maximum is just over 3000, while currently only 600-700 are viable.

**Comment by Seneral** [comment]
Ok scratch all that. It's not even the URL length that's the limit - after exactly 1874 comments the request response ALWAYS contains no content, and no continuation (tested on a video with over 30000 comments) - they know about the URL limitation and decided to just not serve any more coments afterwards, even if with some tricks you could still get more.

This is very annoying. Especially since they don't provide a comment-search feature build-in (which honestly would be of great interest).

**Comment by omarroth** [comment]
> I am developing my own YouTube frontend rn

I would be interested in seeing this if the source is available somewhere.

It's possible to get around the 8k limit by moving the continuation into the request body as `page_token`:

```curl
curl 'https://www.youtube.com/comment_service_ajax?action_get_comments=1' --data 'page_token=EiYSC2tKUVA...&session_token=QUFF...' --compressed
```

However this also has the 1900 limit. Attempting to load further comments on YouTube will result in a 503. YouTube has similar restrictions on the channel page, which will only show a maximum of [3000 videos](https://invidio.us/channel/UCsLiV4WJfkTEHH0b9PmRklw?page=50) (Note there is an equivalent [playlist page](https://invidio.us/playlist?list=UUsLiV4WJfkTEHH0b9PmRklw&page=6248) without this limit, but will not show all videos in some cases).

**Comment by Seneral** [comment]
Ah didn't know about page_token - just observed YouTubes network and didn't find that. Thanks!
<details><summary>Custom youtube frontend</summary>
It's a small project I did over exam phase, really more out of fun that necissity. It's working though, looks very close to youtube (so might need to change that before publishing), logic is completely frontend javascript (except a modified cors-anywhere node.js server) and in total it's around 80kB right now (no third party code/player used).
Could release it right now but it still misses minor stuff like related video and channel video continuation, some mobile optimizations, page options (not video options), etc. Also not using MSE right now, just some hacky sync code that doesn't really work above 720p...
Motivation was to have a functional lightweight music player to experiment with, that can run locally and hosted. Will probably extend it heavily in a separate branch later on.
Goal is to release it sometimes the next few days.
</details>

**Comment by Seneral** [comment]
@omarroth It's published now:
https://github.com/Seneral/FlagPlayer
https://www.seneral.dev/FlagPlayer/
