### ISSUE TITLE
Player makes range requests, YouTube responds with incorrect content lengths

### ISSUE THREAD

**Issue by TheAssassin** [iv-org/invidious#750]
As mentioned over at https://github.com/TeamNewPipe/NewPipe/issues/2615#issuecomment-530447252, I discovered an issue with a few selective videos on YouTube which I tried to play back on invidious. I couldn't recall the exact URLs I used back then, but after looking a bit, I found one that is broken.

On https://invidio.us/watch?v=ppuKO2W9D_8, the following log is produced:

![screenshot_2019-09-12_15-25-22](https://user-images.githubusercontent.com/4503202/64787855-a6ebc200-d571-11e9-9a16-509c10e1c687.png)

My initial assumption that YouTube was trying to be annoying here seems to be unsubstantiated, since the DASH playback version (`&quality=dash`, which by the way should IMO be the default) works just fine.

I couldn't find any other broken videos any more, nor could I find out why this is occurring, it just seems to me that YouTube has an issue on this one specific video that is unrelated to invidious. Nevertheless, as @omarroth invited me to post it here, I wanted to do so. Please let me know if you need any further information. Might as well be one of my privacy plugins, I can't tell for sure (they're all the same on all computers). I can try on some other setup later, I plan to test some stuff in some live ISO VM environments where there's vanilla browsers.

**Comment by omarroth** [comment]
This has since been reported by a couple other folks as well. Testing a broken URL with curl returned an empty response body (with the incorrect `Content-Length`), so this appears to be/have been a bug in YouTube's backend, rather than anything browser-specific.

I wouldn't be surprised if TeamNewPipe/NewPipe#2623 also fixed this issue. Unfortunately I'm having trouble getting a new link to test with, so I expect this is likely resolved.

**Comment by omarroth** [comment]
My mistake, I can still reproduce this on some videos. YouTube appears to only be returning the first chunk in this case (which normally includes metadata/initialization info).

It may be an issue that the video is still being processed, although I'm able to reproduce it on videos that are week+ old. :man_shrugging:

**Comment by TheAssassin** [comment]
What's the reason not to use MPEG-DASH by default? It yields a much better quality anyway, and the player can adapt to the network more easily.

**Comment by omarroth** [comment]
See #616. The main reason is because streams need to be proxied, which puts more load on the instance.

**Comment by TheAssassin** [comment]
Interesting. Not sure why proxying would be needed, NewPipe doesn't proxy either. But I guess you have your reasons.

**Comment by omarroth** [comment]
There's some more info in [this comment](https://github.com/omarroth/invidious/issues/177#issuecomment-423843512) as well. Browsers enforce [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) which means it isn't possible to work with streams from YouTube directly, at least for the APIs needed to combine audio+video.

youtube-dl, FreeTube, NewPipe, etc. don't have to worry about this, since they have much more control over the requests they make.

**Comment by TheAssassin** [comment]
Ah, I see. Was looking for a reason in the issues, but must've missed that comment. Makes perfect sense, and is really annoying.

Proxying is kind of dangerous, depending on the copyright laws this might be serving unauthorized copies...

I guess we finally need a desktop app built upon NewPipe(Extractor) or whatever backend that can handle CORS issues.

**Comment by omarroth** [comment]
Testing a bit more, I'm only able to reproduce with files in format `itag=22` (hd720, mp4). The URLs provided in #782 similarly appear to be in this format.

**Comment by Perflyst** [comment]
More broken videos:
https://invidious.snopyta.org/watch?v=q2cbCsy9gRk
https://invidious.snopyta.org/watch?v=VCImrMSTOvI
