### ISSUE TITLE
can invidio.us be installed on macOS?

### ISSUE THREAD

**Issue by skippingrock** [iv-org/invidious#834]
Title says it all…
can invidio.us be installed on macOS?

**Comment by omarroth** [comment]
Sure, you should be able to get everything you need from [homebrew](brew.sh).

There used to be [instructions for MacOS](https://github.com/omarroth/invidious/blob/b686d76d8cc0fa590f7ff45c1aa1352cf02cf5a0/README.md) which were removed since I unfortunately no longer have a device I can test with.

Something like this should work:
```
$ brew install crystal-lang postgresql imagemagick ...

$ git clone https://github.com/omarroth/invidious
$ cd invidious
$ shards

# Setup postgres user
$ ...

$ psql invidious < config/sql/...
$ crystal build src/invidious.cr --release
$ ./invidious
[development] Kemal is ready to lead at http://0.0.0.0:3000
```

Alternatively, you can also use [docker-compose](https://formulae.brew.sh/formula/docker-compose#default) using the existing instructions in the README.

**Comment by EnricoMonese** [comment]
I think it's just `crystal` for homebrew, not `crystal-lang` anymore
