### ISSUE TITLE
Autoplay should be a default option (at least on invidio.us)

### ISSUE THREAD

**Issue by ulm27661** [iv-org/invidious#905]
I know it's more like personal taste but if I already clicked this video then I want to watch it and this extra click to play is pretty annoying in the long run. I know, I know, I can change it in options. But this solution doesn't work if you have some sort of cookies cleaner where you can't set any exceptions.

This whole disabled autoplay by default is perhaps a good idea but only when you use some sort of addon which replace any youtube video with invidious one. But this is only for embedded videos while on invidio.us it's unnecessary and irritating. 

It's also pretty weird to have this option disabled by default yet having autoplay next video enabled.

**Comment by Perflyst** [comment]
No autoplay is even the default in Firefox, I am against this change.

**Comment by ulm27661** [comment]
So you open a video, go to its tab but you don't want to watch it. You want to click one more time just because clicking is so much fun. Sorry but I don't get it. It's not about some sort of autoplay ad on random webpage it's about watching a video you clicked by yourself.

**Comment by Perflyst** [comment]
You never know if you click it for yourself or if some spooky website just displays it.

**Comment by elypter** [comment]
you might also just want to view the comments and not have audio blasting around you instantly or wasting your mobile bandwidth. i understand your concern but thats what the settings are for. just use an addon that allows you to set exceptions for cookie cleaning. invidio.us can't fix the shortcomings of your browser. maybe you can convince the browser or addon maker to implement this feature. it might not happen but it's worth a try and it would be the right place to solve the problem.

**Comment by Vagmer** [comment]
Invidious is plenty flexible when it comes to supplying or turning on/off options: you can either 1) include them in the URL as a parameter 2) when logged out, select them in options and save & supply them via cookie 3) when logged in, select them in options and have them apply to your Invidious account.

Option 1 is the most portable (will apply to every instance even if it's your first time on it), you can do this by adding `&autoplay=1` to the URL. The [Invidition](https://addons.mozilla.org/en-US/firefox/addon/invidition/) extension can do this automatically for you, among lotsa other things (e.g. do you also want always-on-dark-mode across every instance?), and I generally recommend using it anyway.

Note that, as mentioned, Firefox by default blocks autoplay for all sites (overall across the whole web, this turns out to be very user-friendly). So if you're using Firefox you will probably also need to, in addition to one of methods 1)-3) above, also allow autoplay in FF for the instance(s) you're using, or globally for all sites.

**Comment by 5a384507-18ce-417c-bb55-d4dfcc8883fe** [comment]
Please no.

**Comment by SuperSandro2000** [comment]
> turns out to be very user-friendly

Except if you are on a streaming site and only want to listen to stuff.

Fixing something with yet another extension is not really solving the problem and slowing down the browser. I already have way to many installed and do not wish to add yet another one just for something so basic.

**Comment by syeopite** [comment]
This is irreverent after September 1st 2020.
